package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccessLog<M extends BaseAccessLog<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setAccessRecorderId(java.lang.Long accessRecorderId) {
		set("ACCESS_RECORDER_ID", accessRecorderId);
	}
	
	/**
	 * ID
	 */
	public java.lang.Long getAccessRecorderId() {
		return getLong("ACCESS_RECORDER_ID");
	}

	/**
	 * 用户的ip
	 */
	public void setFmWhere(java.lang.String fmWhere) {
		set("FM_WHERE", fmWhere);
	}
	
	/**
	 * 用户的ip
	 */
	public java.lang.String getFmWhere() {
		return getStr("FM_WHERE");
	}

	/**
	 * 系统的URI
	 */
	public void setAccessUri(java.lang.String accessUri) {
		set("ACCESS_URI", accessUri);
	}
	
	/**
	 * 系统的URI
	 */
	public java.lang.String getAccessUri() {
		return getStr("ACCESS_URI");
	}

	/**
	 * 访问的时间
	 */
	public void setAccessDt(java.util.Date accessDt) {
		set("ACCESS_DT", accessDt);
	}
	
	/**
	 * 访问的时间
	 */
	public java.util.Date getAccessDt() {
		return get("ACCESS_DT");
	}

}
