package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 更新时间
	 */
	public void setUpdDte(java.lang.String updDte) {
		set("UPD_DTE", updDte);
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.String getUpdDte() {
		return getStr("UPD_DTE");
	}

	/**
	 * 更新人
	 */
	public void setUpdUsr(java.lang.String updUsr) {
		set("UPD_USR", updUsr);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.String getUpdUsr() {
		return getStr("UPD_USR");
	}

	/**
	 * 标题
	 */
	public void setArticleTitle(java.lang.String articleTitle) {
		set("ARTICLE_TITLE", articleTitle);
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getArticleTitle() {
		return getStr("ARTICLE_TITLE");
	}

	/**
	 * 关键字
	 */
	public void setArticleKeywd(java.lang.String articleKeywd) {
		set("ARTICLE_KEYWD", articleKeywd);
	}
	
	/**
	 * 关键字
	 */
	public java.lang.String getArticleKeywd() {
		return getStr("ARTICLE_KEYWD");
	}

	/**
	 * 内容
	 */
	public void setCTENT(java.lang.String CTENT) {
		set("CTENT", CTENT);
	}
	
	/**
	 * 内容
	 */
	public java.lang.String getCTENT() {
		return getStr("CTENT");
	}

}
