package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUpload<M extends BaseUpload<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 来源类型
	 */
	public void setRefTyp(java.lang.String refTyp) {
		set("REF_TYP", refTyp);
	}
	
	/**
	 * 来源类型
	 */
	public java.lang.String getRefTyp() {
		return getStr("REF_TYP");
	}

	/**
	 * 来源ID
	 */
	public void setRefId(java.lang.Long refId) {
		set("REF_ID", refId);
	}
	
	/**
	 * 来源ID
	 */
	public java.lang.Long getRefId() {
		return getLong("REF_ID");
	}

	/**
	 * 来源描述
	 */
	public void setRefTitle(java.lang.String refTitle) {
		set("REF_TITLE", refTitle);
	}
	
	/**
	 * 来源描述
	 */
	public java.lang.String getRefTitle() {
		return getStr("REF_TITLE");
	}

	/**
	 * 文件名
	 */
	public void setFileNme(java.lang.String fileNme) {
		set("FILE_NME", fileNme);
	}
	
	/**
	 * 文件名
	 */
	public java.lang.String getFileNme() {
		return getStr("FILE_NME");
	}

	/**
	 * 描述
	 */
	public void setCTENT(java.lang.String CTENT) {
		set("CTENT", CTENT);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getCTENT() {
		return getStr("CTENT");
	}

	/**
	 * 物料路径
	 */
	public void setFileLoc(java.lang.String fileLoc) {
		set("FILE_LOC", fileLoc);
	}
	
	/**
	 * 物料路径
	 */
	public java.lang.String getFileLoc() {
		return getStr("FILE_LOC");
	}

	/**
	 * 上载时间
	 */
	public void setCreDte(java.lang.String creDte) {
		set("CRE_DTE", creDte);
	}
	
	/**
	 * 上载时间
	 */
	public java.lang.String getCreDte() {
		return getStr("CRE_DTE");
	}

	/**
	 * 上载人
	 */
	public void setCreUsr(java.lang.String creUsr) {
		set("CRE_USR", creUsr);
	}
	
	/**
	 * 上载人
	 */
	public java.lang.String getCreUsr() {
		return getStr("CRE_USR");
	}

}
