package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFileMgmt<M extends BaseFileMgmt<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 文件名
	 */
	public void setFileNme(java.lang.String fileNme) {
		set("FILE_NME", fileNme);
	}
	
	/**
	 * 文件名
	 */
	public java.lang.String getFileNme() {
		return getStr("FILE_NME");
	}

	/**
	 * 是否是目录：N/Y
	 */
	public void setIsDir(java.lang.String isDir) {
		set("IS_DIR", isDir);
	}
	
	/**
	 * 是否是目录：N/Y
	 */
	public java.lang.String getIsDir() {
		return getStr("IS_DIR");
	}

	/**
	 * 文件层级
	 */
	public void setDEPTH(java.lang.Integer DEPTH) {
		set("DEPTH", DEPTH);
	}
	
	/**
	 * 文件层级
	 */
	public java.lang.Integer getDEPTH() {
		return getInt("DEPTH");
	}

	/**
	 * 直接上级ID
	 */
	public void setParentId(java.lang.Long parentId) {
		set("PARENT_ID", parentId);
	}
	
	/**
	 * 直接上级ID
	 */
	public java.lang.Long getParentId() {
		return getLong("PARENT_ID");
	}

	/**
	 * 最后修改人
	 */
	public void setUpdUsr(java.lang.String updUsr) {
		set("UPD_USR", updUsr);
	}
	
	/**
	 * 最后修改人
	 */
	public java.lang.String getUpdUsr() {
		return getStr("UPD_USR");
	}

	/**
	 * 最后修改时间
	 */
	public void setUpdDte(java.lang.String updDte) {
		set("UPD_DTE", updDte);
	}
	
	/**
	 * 最后修改时间
	 */
	public java.lang.String getUpdDte() {
		return getStr("UPD_DTE");
	}

	/**
	 * 来源ID
	 */
	public void setRefId(java.lang.Long refId) {
		set("REF_ID", refId);
	}
	
	/**
	 * 来源ID
	 */
	public java.lang.Long getRefId() {
		return getLong("REF_ID");
	}

	/**
	 * 描述
	 */
	public void setCTENT(java.lang.String CTENT) {
		set("CTENT", CTENT);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getCTENT() {
		return getStr("CTENT");
	}

	/**
	 * 状态：正常A、待发布P、历史H、删除D
	 */
	public void setSTS(java.lang.String STS) {
		set("STS", STS);
	}
	
	/**
	 * 状态：正常A、待发布P、历史H、删除D
	 */
	public java.lang.String getSTS() {
		return getStr("STS");
	}

	/**
	 * 对应的物理路径，只针对 Depth=0时有用
	 */
	public void setAbsPath(java.lang.String absPath) {
		set("ABS_PATH", absPath);
	}
	
	/**
	 * 对应的物理路径，只针对 Depth=0时有用
	 */
	public java.lang.String getAbsPath() {
		return getStr("ABS_PATH");
	}

}
