package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePosts<M extends BasePosts<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	public void setCMMT(java.lang.String CMMT) {
		set("CMMT", CMMT);
	}
	
	public java.lang.String getCMMT() {
		return getStr("CMMT");
	}

	public void setAUTHOR(java.lang.String AUTHOR) {
		set("AUTHOR", AUTHOR);
	}
	
	public java.lang.String getAUTHOR() {
		return getStr("AUTHOR");
	}

}
