package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAsset<M extends BaseAsset<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 资产编号
	 */
	public void setAssetNum(java.lang.String assetNum) {
		set("ASSET_NUM", assetNum);
	}
	
	/**
	 * 资产编号
	 */
	public java.lang.String getAssetNum() {
		return getStr("ASSET_NUM");
	}

	/**
	 * 资产名称
	 */
	public void setAssetNme(java.lang.String assetNme) {
		set("ASSET_NME", assetNme);
	}
	
	/**
	 * 资产名称
	 */
	public java.lang.String getAssetNme() {
		return getStr("ASSET_NME");
	}

	/**
	 * 资产购置日期
	 */
	public void setAssetDte(java.lang.String assetDte) {
		set("ASSET_DTE", assetDte);
	}
	
	/**
	 * 资产购置日期
	 */
	public java.lang.String getAssetDte() {
		return getStr("ASSET_DTE");
	}

	/**
	 * 资产使用部门
	 */
	public void setOwnDept(java.lang.String ownDept) {
		set("OWN_DEPT", ownDept);
	}
	
	/**
	 * 资产使用部门
	 */
	public java.lang.String getOwnDept() {
		return getStr("OWN_DEPT");
	}

	/**
	 * 资产使用人
	 */
	public void setOwnUsr(java.lang.String ownUsr) {
		set("OWN_USR", ownUsr);
	}
	
	/**
	 * 资产使用人
	 */
	public java.lang.String getOwnUsr() {
		return getStr("OWN_USR");
	}

	/**
	 * 资产管理员
	 */
	public void setAssetKeeper(java.lang.String assetKeeper) {
		set("ASSET_KEEPER", assetKeeper);
	}
	
	/**
	 * 资产管理员
	 */
	public java.lang.String getAssetKeeper() {
		return getStr("ASSET_KEEPER");
	}

	/**
	 * 资产位置
	 */
	public void setAssetLoc(java.lang.String assetLoc) {
		set("ASSET_LOC", assetLoc);
	}
	
	/**
	 * 资产位置
	 */
	public java.lang.String getAssetLoc() {
		return getStr("ASSET_LOC");
	}

	/**
	 * 备注
	 */
	public void setRMK(java.lang.String RMK) {
		set("RMK", RMK);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRMK() {
		return getStr("RMK");
	}

}
