package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRdrecords32<M extends BaseRdrecords32<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	public void setRDRECORDID(java.lang.Long RDRECORDID) {
		set("RDRECORDID", RDRECORDID);
	}
	
	public java.lang.Long getRDRECORDID() {
		return getLong("RDRECORDID");
	}

	public void setISOSID(java.lang.Long ISOSID) {
		set("ISOSID", ISOSID);
	}
	
	public java.lang.Long getISOSID() {
		return getLong("ISOSID");
	}

	public void setIQUANTITY(java.lang.String IQUANTITY) {
		set("IQUANTITY", IQUANTITY);
	}
	
	public java.lang.String getIQUANTITY() {
		return getStr("IQUANTITY");
	}

	public void setCDEFINE28(java.lang.String CDEFINE28) {
		set("CDEFINE28", CDEFINE28);
	}
	
	public java.lang.String getCDEFINE28() {
		return getStr("CDEFINE28");
	}

	public void setCINVCODE(java.lang.String CINVCODE) {
		set("CINVCODE", CINVCODE);
	}
	
	public java.lang.String getCINVCODE() {
		return getStr("CINVCODE");
	}

	public void setCitemClass(java.lang.String citemClass) {
		set("CITEM_CLASS", citemClass);
	}
	
	public java.lang.String getCitemClass() {
		return getStr("CITEM_CLASS");
	}

	public void setCITEMCNAME(java.lang.String CITEMCNAME) {
		set("CITEMCNAME", CITEMCNAME);
	}
	
	public java.lang.String getCITEMCNAME() {
		return getStr("CITEMCNAME");
	}

	public void setCITEMCODE(java.lang.String CITEMCODE) {
		set("CITEMCODE", CITEMCODE);
	}
	
	public java.lang.String getCITEMCODE() {
		return getStr("CITEMCODE");
	}

	public void setCNAME(java.lang.String CNAME) {
		set("CNAME", CNAME);
	}
	
	public java.lang.String getCNAME() {
		return getStr("CNAME");
	}

}
