package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBpmInsNode<M extends BaseBpmInsNode<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 审批实例ID
	 */
	public void setInsId(java.lang.Long insId) {
		set("INS_ID", insId);
	}
	
	/**
	 * 审批实例ID
	 */
	public java.lang.Long getInsId() {
		return getLong("INS_ID");
	}

	/**
	 * 审批节点次序
	 */
	public void setStepNum(java.lang.Integer stepNum) {
		set("STEP_NUM", stepNum);
	}
	
	/**
	 * 审批节点次序
	 */
	public java.lang.Integer getStepNum() {
		return getInt("STEP_NUM");
	}

	/**
	 * 审批规则：一票过，一票否，第一人
	 */
	public void setCalcRule(java.lang.String calcRule) {
		set("CALC_RULE", calcRule);
	}
	
	/**
	 * 审批规则：一票过，一票否，第一人
	 */
	public java.lang.String getCalcRule() {
		return getStr("CALC_RULE");
	}

	/**
	 * 节点审批人
	 */
	public void setCurrUsr(java.lang.String currUsr) {
		set("CURR_USR", currUsr);
	}
	
	/**
	 * 节点审批人
	 */
	public java.lang.String getCurrUsr() {
		return getStr("CURR_USR");
	}

	/**
	 * 审批人的审批结果
	 */
	public void setCurrResult(java.lang.String currResult) {
		set("CURR_RESULT", currResult);
	}
	
	/**
	 * 审批人的审批结果
	 */
	public java.lang.String getCurrResult() {
		return getStr("CURR_RESULT");
	}

	/**
	 * 审批意见
	 */
	public void setCurrRmk(java.lang.String currRmk) {
		set("CURR_RMK", currRmk);
	}
	
	/**
	 * 审批意见
	 */
	public java.lang.String getCurrRmk() {
		return getStr("CURR_RMK");
	}

	/**
	 * 到达本节点的时间
	 */
	public void setArrDte(java.lang.String arrDte) {
		set("ARR_DTE", arrDte);
	}
	
	/**
	 * 到达本节点的时间
	 */
	public java.lang.String getArrDte() {
		return getStr("ARR_DTE");
	}

	/**
	 * 本节点处理完成的时间
	 */
	public void setCmplDte(java.lang.String cmplDte) {
		set("CMPL_DTE", cmplDte);
	}
	
	/**
	 * 本节点处理完成的时间
	 */
	public java.lang.String getCmplDte() {
		return getStr("CMPL_DTE");
	}

}
