package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePerson<M extends BasePerson<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setFirstName(java.lang.String firstName) {
		set("first_name", firstName);
	}
	
	public java.lang.String getFirstName() {
		return getStr("first_name");
	}

	public void setLastName(java.lang.String lastName) {
		set("last_name", lastName);
	}
	
	public java.lang.String getLastName() {
		return getStr("last_name");
	}

}
