package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAddress<M extends BaseAddress<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 详细地址
	 */
	public void setFull(java.lang.String full) {
		set("full", full);
	}
	
	/**
	 * 详细地址
	 */
	public java.lang.String getFull() {
		return getStr("full");
	}

	/**
	 * 手机
	 */
	public void setMobilephone(java.lang.String mobilephone) {
		set("mobilephone", mobilephone);
	}
	
	/**
	 * 手机
	 */
	public java.lang.String getMobilephone() {
		return getStr("mobilephone");
	}

}
