package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDlyTask<M extends BaseDlyTask<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 人员名
	 */
	public void setUsrNme(java.lang.String usrNme) {
		set("USR_NME", usrNme);
	}
	
	/**
	 * 人员名
	 */
	public java.lang.String getUsrNme() {
		return getStr("USR_NME");
	}

	/**
	 * 日期 YYYY-MM-dd
	 */
	public void setBizDte(java.lang.String bizDte) {
		set("BIZ_DTE", bizDte);
	}
	
	/**
	 * 日期 YYYY-MM-dd
	 */
	public java.lang.String getBizDte() {
		return getStr("BIZ_DTE");
	}

	/**
	 * 工作内容
	 */
	public void setWorkRmk(java.lang.String workRmk) {
		set("WORK_RMK", workRmk);
	}
	
	/**
	 * 工作内容
	 */
	public java.lang.String getWorkRmk() {
		return getStr("WORK_RMK");
	}

	/**
	 * 最新更新日期
	 */
	public void setUpdDte(java.lang.String updDte) {
		set("UPD_DTE", updDte);
	}
	
	/**
	 * 最新更新日期
	 */
	public java.lang.String getUpdDte() {
		return getStr("UPD_DTE");
	}

}
