package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDiskspace<M extends BaseDiskspace<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 服务器说明
	 */
	public void setSrvrNme(java.lang.String srvrNme) {
		set("SRVR_NME", srvrNme);
	}
	
	/**
	 * 服务器说明
	 */
	public java.lang.String getSrvrNme() {
		return getStr("SRVR_NME");
	}

	/**
	 * 服务器地址
	 */
	public void setSrvrIp(java.lang.String srvrIp) {
		set("SRVR_IP", srvrIp);
	}
	
	/**
	 * 服务器地址
	 */
	public java.lang.String getSrvrIp() {
		return getStr("SRVR_IP");
	}

	/**
	 * 盘符
	 */
	public void setDiskNme(java.lang.String diskNme) {
		set("DISK_NME", diskNme);
	}
	
	/**
	 * 盘符
	 */
	public java.lang.String getDiskNme() {
		return getStr("DISK_NME");
	}

	/**
	 * 剩余空间占总空间的比例小于时，触发预警
	 */
	public void setWarningPt(java.lang.Integer warningPt) {
		set("WARNING_PT", warningPt);
	}
	
	/**
	 * 剩余空间占总空间的比例小于时，触发预警
	 */
	public java.lang.Integer getWarningPt() {
		return getInt("WARNING_PT");
	}

	/**
	 * 通知人
	 */
	public void setNoticeUsr(java.lang.String noticeUsr) {
		set("NOTICE_USR", noticeUsr);
	}
	
	/**
	 * 通知人
	 */
	public java.lang.String getNoticeUsr() {
		return getStr("NOTICE_USR");
	}

	/**
	 * 最近一次访问的时间
	 */
	public void setLTick(java.lang.String lTick) {
		set("L_TICK", lTick);
	}
	
	/**
	 * 最近一次访问的时间
	 */
	public java.lang.String getLTick() {
		return getStr("L_TICK");
	}

	/**
	 * 最近一次总容量
	 */
	public void setLTtlAmt(java.lang.Double lTtlAmt) {
		set("L_TTL_AMT", lTtlAmt);
	}
	
	/**
	 * 最近一次总容量
	 */
	public java.lang.Double getLTtlAmt() {
		return getDouble("L_TTL_AMT");
	}

	/**
	 * 最近一次可用容量
	 */
	public void setLFreeAmt(java.lang.Double lFreeAmt) {
		set("L_FREE_AMT", lFreeAmt);
	}
	
	/**
	 * 最近一次可用容量
	 */
	public java.lang.Double getLFreeAmt() {
		return getDouble("L_FREE_AMT");
	}

	/**
	 * 邮件通知是否激活 ACTIVE/DEACTIVE
	 */
	public void setStsInd(java.lang.String stsInd) {
		set("STS_IND", stsInd);
	}
	
	/**
	 * 邮件通知是否激活 ACTIVE/DEACTIVE
	 */
	public java.lang.String getStsInd() {
		return getStr("STS_IND");
	}

}
