package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFeedback<M extends BaseFeedback<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 来源类型
	 */
	public void setRefTyp(java.lang.String refTyp) {
		set("REF_TYP", refTyp);
	}
	
	/**
	 * 来源类型
	 */
	public java.lang.String getRefTyp() {
		return getStr("REF_TYP");
	}

	/**
	 * 来源ID
	 */
	public void setRefId(java.lang.Long refId) {
		set("REF_ID", refId);
	}
	
	/**
	 * 来源ID
	 */
	public java.lang.Long getRefId() {
		return getLong("REF_ID");
	}

	/**
	 * 来源描述
	 */
	public void setRefTitle(java.lang.String refTitle) {
		set("REF_TITLE", refTitle);
	}
	
	/**
	 * 来源描述
	 */
	public java.lang.String getRefTitle() {
		return getStr("REF_TITLE");
	}

	/**
	 * 反馈信息
	 */
	public void setCMMT(java.lang.String CMMT) {
		set("CMMT", CMMT);
	}
	
	/**
	 * 反馈信息
	 */
	public java.lang.String getCMMT() {
		return getStr("CMMT");
	}

	/**
	 * 反馈人
	 */
	public void setCreUsr(java.lang.String creUsr) {
		set("CRE_USR", creUsr);
	}
	
	/**
	 * 反馈人
	 */
	public java.lang.String getCreUsr() {
		return getStr("CRE_USR");
	}

	/**
	 * 反馈时间
	 */
	public void setCreDte(java.lang.String creDte) {
		set("CRE_DTE", creDte);
	}
	
	/**
	 * 反馈时间
	 */
	public java.lang.String getCreDte() {
		return getStr("CRE_DTE");
	}

}
