package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDept<M extends BaseDept<M>> extends Model<M> implements IBean {

	public void setDeptId(java.lang.Long deptId) {
		set("DEPT_ID", deptId);
	}
	
	public java.lang.Long getDeptId() {
		return getLong("DEPT_ID");
	}

	/**
	 * 部门代码
	 */
	public void setDeptCde(java.lang.String deptCde) {
		set("DEPT_CDE", deptCde);
	}
	
	/**
	 * 部门代码
	 */
	public java.lang.String getDeptCde() {
		return getStr("DEPT_CDE");
	}

	/**
	 * 部门名称
	 */
	public void setDeptNme(java.lang.String deptNme) {
		set("DEPT_NME", deptNme);
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getDeptNme() {
		return getStr("DEPT_NME");
	}

	public void setDispSeq(java.lang.Integer dispSeq) {
		set("DISP_SEQ", dispSeq);
	}
	
	public java.lang.Integer getDispSeq() {
		return getInt("DISP_SEQ");
	}

	public void setDeptHead(java.lang.String deptHead) {
		set("DEPT_HEAD", deptHead);
	}
	
	public java.lang.String getDeptHead() {
		return getStr("DEPT_HEAD");
	}

	public void setParentId(java.lang.Long parentId) {
		set("PARENT_ID", parentId);
	}
	
	public java.lang.Long getParentId() {
		return getLong("PARENT_ID");
	}

}
