package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCountry<M extends BaseCountry<M>> extends Model<M> implements IBean {

	public void setCode(java.lang.String Code) {
		set("Code", Code);
	}
	
	public java.lang.String getCode() {
		return getStr("Code");
	}

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}
	
	public java.lang.String getName() {
		return getStr("Name");
	}

	public void setContinent(java.lang.String Continent) {
		set("Continent", Continent);
	}
	
	public java.lang.String getContinent() {
		return getStr("Continent");
	}

	public void setRegion(java.lang.String Region) {
		set("Region", Region);
	}
	
	public java.lang.String getRegion() {
		return getStr("Region");
	}

	public void setSurfaceArea(java.lang.Float SurfaceArea) {
		set("SurfaceArea", SurfaceArea);
	}
	
	public java.lang.Float getSurfaceArea() {
		return getFloat("SurfaceArea");
	}

	public void setIndepYear(java.lang.Integer IndepYear) {
		set("IndepYear", IndepYear);
	}
	
	public java.lang.Integer getIndepYear() {
		return getInt("IndepYear");
	}

	public void setPopulation(java.lang.Integer Population) {
		set("Population", Population);
	}
	
	public java.lang.Integer getPopulation() {
		return getInt("Population");
	}

	public void setLifeExpectancy(java.lang.Float LifeExpectancy) {
		set("LifeExpectancy", LifeExpectancy);
	}
	
	public java.lang.Float getLifeExpectancy() {
		return getFloat("LifeExpectancy");
	}

	public void setGNP(java.lang.Float GNP) {
		set("GNP", GNP);
	}
	
	public java.lang.Float getGNP() {
		return getFloat("GNP");
	}

	public void setGNPOld(java.lang.Float GNPOld) {
		set("GNPOld", GNPOld);
	}
	
	public java.lang.Float getGNPOld() {
		return getFloat("GNPOld");
	}

	public void setLocalName(java.lang.String LocalName) {
		set("LocalName", LocalName);
	}
	
	public java.lang.String getLocalName() {
		return getStr("LocalName");
	}

	public void setGovernmentForm(java.lang.String GovernmentForm) {
		set("GovernmentForm", GovernmentForm);
	}
	
	public java.lang.String getGovernmentForm() {
		return getStr("GovernmentForm");
	}

	public void setHeadOfState(java.lang.String HeadOfState) {
		set("HeadOfState", HeadOfState);
	}
	
	public java.lang.String getHeadOfState() {
		return getStr("HeadOfState");
	}

	public void setCapital(java.lang.Integer Capital) {
		set("Capital", Capital);
	}
	
	public java.lang.Integer getCapital() {
		return getInt("Capital");
	}

	public void setCode2(java.lang.String Code2) {
		set("Code2", Code2);
	}
	
	public java.lang.String getCode2() {
		return getStr("Code2");
	}

}
