package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBpmProcessNode<M extends BaseBpmProcessNode<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 流程ID
	 */
	public void setProcessId(java.lang.Long processId) {
		set("PROCESS_ID", processId);
	}
	
	/**
	 * 流程ID
	 */
	public java.lang.Long getProcessId() {
		return getLong("PROCESS_ID");
	}

	/**
	 * 审批节点名称
	 */
	public void setNodeNme(java.lang.String nodeNme) {
		set("NODE_NME", nodeNme);
	}
	
	/**
	 * 审批节点名称
	 */
	public java.lang.String getNodeNme() {
		return getStr("NODE_NME");
	}

	/**
	 * 审批次序
	 */
	public void setStepNum(java.lang.String stepNum) {
		set("STEP_NUM", stepNum);
	}
	
	/**
	 * 审批次序
	 */
	public java.lang.String getStepNum() {
		return getStr("STEP_NUM");
	}

	/**
	 * 节点描述
	 */
	public void setNodeDesc(java.lang.String nodeDesc) {
		set("NODE_DESC", nodeDesc);
	}
	
	/**
	 * 节点描述
	 */
	public java.lang.String getNodeDesc() {
		return getStr("NODE_DESC");
	}

	/**
	 * 节点类型，指定具体用户，定义规则
	 */
	public void setNodeTyp(java.lang.String nodeTyp) {
		set("NODE_TYP", nodeTyp);
	}
	
	/**
	 * 节点类型，指定具体用户，定义规则
	 */
	public java.lang.String getNodeTyp() {
		return getStr("NODE_TYP");
	}

	/**
	 * 具体用户
	 */
	public void setNodeUsr(java.lang.String nodeUsr) {
		set("NODE_USR", nodeUsr);
	}
	
	/**
	 * 具体用户
	 */
	public java.lang.String getNodeUsr() {
		return getStr("NODE_USR");
	}

	/**
	 * 节点规则
	 */
	public void setBizRule(java.lang.String bizRule) {
		set("BIZ_RULE", bizRule);
	}
	
	/**
	 * 节点规则
	 */
	public java.lang.String getBizRule() {
		return getStr("BIZ_RULE");
	}

	/**
	 * 审批规则：一票过，一票否，第一人
	 */
	public void setCalcRule(java.lang.String calcRule) {
		set("CALC_RULE", calcRule);
	}
	
	/**
	 * 审批规则：一票过，一票否，第一人
	 */
	public java.lang.String getCalcRule() {
		return getStr("CALC_RULE");
	}

	/**
	 * 本节点允许操作：同意+拒绝，只能同意
	 */
	public void setBizAction(java.lang.String bizAction) {
		set("BIZ_ACTION", bizAction);
	}
	
	/**
	 * 本节点允许操作：同意+拒绝，只能同意
	 */
	public java.lang.String getBizAction() {
		return getStr("BIZ_ACTION");
	}

	/**
	 * 更新人
	 */
	public void setUpdUsr(java.lang.String updUsr) {
		set("UPD_USR", updUsr);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.String getUpdUsr() {
		return getStr("UPD_USR");
	}

	/**
	 * 更新时间
	 */
	public void setUpdDte(java.lang.String updDte) {
		set("UPD_DTE", updDte);
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.String getUpdDte() {
		return getStr("UPD_DTE");
	}

}
