package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxstats<M extends BaseMxstats<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setBizDate(java.util.Date bizDate) {
		set("biz_date", bizDate);
	}
	
	public java.util.Date getBizDate() {
		return get("biz_date");
	}

	public void setBizTime(java.sql.Time bizTime) {
		set("biz_time", bizTime);
	}
	
	public java.sql.Time getBizTime() {
		return get("biz_time");
	}

	public void setBlNum(java.lang.String blNum) {
		set("bl_num", blNum);
	}
	
	public java.lang.String getBlNum() {
		return getStr("bl_num");
	}

	public void setCustNme(java.lang.String custNme) {
		set("cust_nme", custNme);
	}
	
	public java.lang.String getCustNme() {
		return getStr("cust_nme");
	}

}
