package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEvent<M extends BaseEvent<M>> extends Model<M> implements IBean {

	public void setEvtId(java.lang.Long evtId) {
		set("EVT_ID", evtId);
	}
	
	public java.lang.Long getEvtId() {
		return getLong("EVT_ID");
	}

	/**
	 * 事件类型
	 */
	public void setTYP(java.lang.String TYP) {
		set("TYP", TYP);
	}
	
	/**
	 * 事件类型
	 */
	public java.lang.String getTYP() {
		return getStr("TYP");
	}

	/**
	 * 主导部门
	 */
	public void setDEPT(java.lang.String DEPT) {
		set("DEPT", DEPT);
	}
	
	/**
	 * 主导部门
	 */
	public java.lang.String getDEPT() {
		return getStr("DEPT");
	}

	/**
	 * 召集人
	 */
	public void setUsrId(java.lang.Long usrId) {
		set("USR_ID", usrId);
	}
	
	/**
	 * 召集人
	 */
	public java.lang.Long getUsrId() {
		return getLong("USR_ID");
	}

	/**
	 * 召集人
	 */
	public void setUsrNme(java.lang.String usrNme) {
		set("USR_NME", usrNme);
	}
	
	/**
	 * 召集人
	 */
	public java.lang.String getUsrNme() {
		return getStr("USR_NME");
	}

	/**
	 * 发生日期
	 */
	public void setEvtDt(java.lang.String evtDt) {
		set("EVT_DT", evtDt);
	}
	
	/**
	 * 发生日期
	 */
	public java.lang.String getEvtDt() {
		return getStr("EVT_DT");
	}

	/**
	 * 发生地点
	 */
	public void setPLACE(java.lang.String PLACE) {
		set("PLACE", PLACE);
	}
	
	/**
	 * 发生地点
	 */
	public java.lang.String getPLACE() {
		return getStr("PLACE");
	}

	/**
	 * 事件主题
	 */
	public void setSUBJ(java.lang.String SUBJ) {
		set("SUBJ", SUBJ);
	}
	
	/**
	 * 事件主题
	 */
	public java.lang.String getSUBJ() {
		return getStr("SUBJ");
	}

	/**
	 * 事件记录
	 */
	public void setMEMO(java.lang.String MEMO) {
		set("MEMO", MEMO);
	}
	
	/**
	 * 事件记录
	 */
	public java.lang.String getMEMO() {
		return getStr("MEMO");
	}

	/**
	 * 创建人
	 */
	public void setCreUsr(java.lang.String creUsr) {
		set("CRE_USR", creUsr);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreUsr() {
		return getStr("CRE_USR");
	}

	/**
	 * 创建时间
	 */
	public void setCreDt(java.lang.String creDt) {
		set("CRE_DT", creDt);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreDt() {
		return getStr("CRE_DT");
	}

	/**
	 * 修改人
	 */
	public void setUpdUsr(java.lang.String updUsr) {
		set("UPD_USR", updUsr);
	}
	
	/**
	 * 修改人
	 */
	public java.lang.String getUpdUsr() {
		return getStr("UPD_USR");
	}

	/**
	 * 修改时间
	 */
	public void setUpdDt(java.lang.String updDt) {
		set("UPD_DT", updDt);
	}
	
	/**
	 * 修改时间
	 */
	public java.lang.String getUpdDt() {
		return getStr("UPD_DT");
	}

	/**
	 * 料号信息
	 */
	public void setMatrlDesc(java.lang.String matrlDesc) {
		set("MATRL_DESC", matrlDesc);
	}
	
	/**
	 * 料号信息
	 */
	public java.lang.String getMatrlDesc() {
		return getStr("MATRL_DESC");
	}

	public void setEventStatus(java.lang.String eventStatus) {
		set("EVENT_STATUS", eventStatus);
	}
	
	public java.lang.String getEventStatus() {
		return getStr("EVENT_STATUS");
	}

}
