package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicts<M extends BaseDicts<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 字典值
	 */
	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	/**
	 * 字典值
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}

	/**
	 * 字典中文
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 字典中文
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 表名
	 */
	public void setObject(java.lang.String object) {
		set("object", object);
	}
	
	/**
	 * 表名
	 */
	public java.lang.String getObject() {
		return getStr("object");
	}

	/**
	 * 字段名
	 */
	public void setField(java.lang.String field) {
		set("field", field);
	}
	
	/**
	 * 字段名
	 */
	public java.lang.String getField() {
		return getStr("field");
	}

	/**
	 * 扩展Json
	 */
	public void setExt(java.lang.String ext) {
		set("ext", ext);
	}
	
	/**
	 * 扩展Json
	 */
	public java.lang.String getExt() {
		return getStr("ext");
	}

}
