package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAreaCity<M extends BaseAreaCity<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 父级编码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 父级编码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

}
