package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSoItm<M extends BaseSoItm<M>> extends Model<M> implements IBean {

	/**
	 * 销售订单行项目
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 销售订单行项目
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 销售订单
	 */
	public void setSoId(java.lang.Long soId) {
		set("soId", soId);
	}
	
	/**
	 * 销售订单
	 */
	public java.lang.Long getSoId() {
		return getLong("soId");
	}

	/**
	 * 销售订单编号
	 */
	public void setOrderNum(java.lang.String orderNum) {
		set("orderNum", orderNum);
	}
	
	/**
	 * 销售订单编号
	 */
	public java.lang.String getOrderNum() {
		return getStr("orderNum");
	}

	/**
	 * 行项目编号
	 */
	public void setItemSeq(java.lang.Long itemSeq) {
		set("itemSeq", itemSeq);
	}
	
	/**
	 * 行项目编号
	 */
	public java.lang.Long getItemSeq() {
		return getLong("itemSeq");
	}

	/**
	 * 下单时间
	 */
	public void setPlaceDate(java.util.Date placeDate) {
		set("placeDate", placeDate);
	}
	
	/**
	 * 下单时间
	 */
	public java.util.Date getPlaceDate() {
		return get("placeDate");
	}

	/**
	 * 客户编号
	 */
	public void setCustomerCode(java.lang.String customerCode) {
		set("customerCode", customerCode);
	}
	
	/**
	 * 客户编号
	 */
	public java.lang.String getCustomerCode() {
		return getStr("customerCode");
	}

	/**
	 * 物料编号
	 */
	public void setMaterialCode(java.lang.String materialCode) {
		set("materialCode", materialCode);
	}
	
	/**
	 * 物料编号
	 */
	public java.lang.String getMaterialCode() {
		return getStr("materialCode");
	}

	/**
	 * 订单数量
	 */
	public void setOrderQty(java.math.BigDecimal orderQty) {
		set("orderQty", orderQty);
	}
	
	/**
	 * 订单数量
	 */
	public java.math.BigDecimal getOrderQty() {
		return get("orderQty");
	}

	/**
	 * 收货人
	 */
	public void setDeliveryCustomer(java.lang.String deliveryCustomer) {
		set("deliveryCustomer", deliveryCustomer);
	}
	
	/**
	 * 收货人
	 */
	public java.lang.String getDeliveryCustomer() {
		return getStr("deliveryCustomer");
	}

	/**
	 * 收货地址
	 */
	public void setDeliveryAddr(java.lang.String deliveryAddr) {
		set("deliveryAddr", deliveryAddr);
	}
	
	/**
	 * 收货地址
	 */
	public java.lang.String getDeliveryAddr() {
		return getStr("deliveryAddr");
	}

	/**
	 * 收货联系电话
	 */
	public void setDeliveryPhone(java.lang.String deliveryPhone) {
		set("deliveryPhone", deliveryPhone);
	}
	
	/**
	 * 收货联系电话
	 */
	public java.lang.String getDeliveryPhone() {
		return getStr("deliveryPhone");
	}

	/**
	 * 已分配库存数量
	 */
	public void setAllocQty(java.math.BigDecimal allocQty) {
		set("allocQty", allocQty);
	}
	
	/**
	 * 已分配库存数量
	 */
	public java.math.BigDecimal getAllocQty() {
		return get("allocQty");
	}

	/**
	 * 已出库数量
	 */
	public void setDeliveryQty(java.math.BigDecimal deliveryQty) {
		set("deliveryQty", deliveryQty);
	}
	
	/**
	 * 已出库数量
	 */
	public java.math.BigDecimal getDeliveryQty() {
		return get("deliveryQty");
	}

	/**
	 * 备注说明
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注说明
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setIsDelivered(java.lang.String isDelivered) {
		set("isDelivered", isDelivered);
	}
	
	public java.lang.String getIsDelivered() {
		return getStr("isDelivered");
	}

	public void setPriorityTick(java.lang.Integer priorityTick) {
		set("priorityTick", priorityTick);
	}
	
	public java.lang.Integer getPriorityTick() {
		return getInt("priorityTick");
	}

}
