package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestingitm<M extends BaseTestingitm<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 测试头ID
	 */
	public void setHeadId(java.lang.Long headId) {
		set("HEAD_ID", headId);
	}
	
	/**
	 * 测试头ID
	 */
	public java.lang.Long getHeadId() {
		return getLong("HEAD_ID");
	}

	/**
	 * 测试项的序号
	 */
	public void setSEQ(java.lang.String SEQ) {
		set("SEQ", SEQ);
	}
	
	/**
	 * 测试项的序号
	 */
	public java.lang.String getSEQ() {
		return getStr("SEQ");
	}

	/**
	 * 测试项名称
	 */
	public void setNME(java.lang.String NME) {
		set("NME", NME);
	}
	
	/**
	 * 测试项名称
	 */
	public java.lang.String getNME() {
		return getStr("NME");
	}

	/**
	 * 上限
	 */
	public void setCELLING(java.lang.String CELLING) {
		set("CELLING", CELLING);
	}
	
	/**
	 * 上限
	 */
	public java.lang.String getCELLING() {
		return getStr("CELLING");
	}

	/**
	 * 下限
	 */
	public void setFLR(java.lang.String FLR) {
		set("FLR", FLR);
	}
	
	/**
	 * 下限
	 */
	public java.lang.String getFLR() {
		return getStr("FLR");
	}

	/**
	 * 测量单位
	 */
	public void setUNIT(java.lang.String UNIT) {
		set("UNIT", UNIT);
	}
	
	/**
	 * 测量单位
	 */
	public java.lang.String getUNIT() {
		return getStr("UNIT");
	}

	/**
	 * 测量值
	 */
	public void setVAL(java.lang.String VAL) {
		set("VAL", VAL);
	}
	
	/**
	 * 测量值
	 */
	public java.lang.String getVAL() {
		return getStr("VAL");
	}

	/**
	 * 测量结果
	 */
	public void setRESULT(java.lang.String RESULT) {
		set("RESULT", RESULT);
	}
	
	/**
	 * 测量结果
	 */
	public java.lang.String getRESULT() {
		return getStr("RESULT");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreDte(java.lang.String creDte) {
		set("CRE_DTE", creDte);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.lang.String getCreDte() {
		return getStr("CRE_DTE");
	}

}
