package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCountrylanguage<M extends BaseCountrylanguage<M>> extends Model<M> implements IBean {

	public void setCountryCode(java.lang.String CountryCode) {
		set("CountryCode", CountryCode);
	}
	
	public java.lang.String getCountryCode() {
		return getStr("CountryCode");
	}

	public void setLanguage(java.lang.String Language) {
		set("Language", Language);
	}
	
	public java.lang.String getLanguage() {
		return getStr("Language");
	}

	public void setIsOfficial(java.lang.String IsOfficial) {
		set("IsOfficial", IsOfficial);
	}
	
	public java.lang.String getIsOfficial() {
		return getStr("IsOfficial");
	}

	public void setPercentage(java.lang.Float Percentage) {
		set("Percentage", Percentage);
	}
	
	public java.lang.Float getPercentage() {
		return getFloat("Percentage");
	}

}
