package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestinghd<M extends BaseTestinghd<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 报告名称
	 */
	public void setTYP(java.lang.String TYP) {
		set("TYP", TYP);
	}
	
	/**
	 * 报告名称
	 */
	public java.lang.String getTYP() {
		return getStr("TYP");
	}

	/**
	 * 产品类型
	 */
	public void setPRODCT(java.lang.String PRODCT) {
		set("PRODCT", PRODCT);
	}
	
	/**
	 * 产品类型
	 */
	public java.lang.String getPRODCT() {
		return getStr("PRODCT");
	}

	/**
	 * 产品序号
	 */
	public void setProdctSn(java.lang.String prodctSn) {
		set("PRODCT_SN", prodctSn);
	}
	
	/**
	 * 产品序号
	 */
	public java.lang.String getProdctSn() {
		return getStr("PRODCT_SN");
	}

	/**
	 * 测试时间
	 */
	public void setTestingDte(java.lang.String testingDte) {
		set("TESTING_DTE", testingDte);
	}
	
	/**
	 * 测试时间
	 */
	public java.lang.String getTestingDte() {
		return getStr("TESTING_DTE");
	}

	/**
	 * 设备号
	 */
	public void setEquipNum(java.lang.String equipNum) {
		set("EQUIP_NUM", equipNum);
	}
	
	/**
	 * 设备号
	 */
	public java.lang.String getEquipNum() {
		return getStr("EQUIP_NUM");
	}

	/**
	 * 作业员
	 */
	public void setOP(java.lang.String OP) {
		set("OP", OP);
	}
	
	/**
	 * 作业员
	 */
	public java.lang.String getOP() {
		return getStr("OP");
	}

	/**
	 * 测试结果
	 */
	public void setRESULT(java.lang.String RESULT) {
		set("RESULT", RESULT);
	}
	
	/**
	 * 测试结果
	 */
	public java.lang.String getRESULT() {
		return getStr("RESULT");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreDte(java.lang.String creDte) {
		set("CRE_DTE", creDte);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.lang.String getCreDte() {
		return getStr("CRE_DTE");
	}

}
