package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCtrctPlan<M extends BaseCtrctPlan<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 合同ID
	 */
	public void setCtrctId(java.lang.String ctrctId) {
		set("CTRCT_ID", ctrctId);
	}
	
	/**
	 * 合同ID
	 */
	public java.lang.String getCtrctId() {
		return getStr("CTRCT_ID");
	}

	/**
	 * 付款计划的名称
	 */
	public void setItmNme(java.lang.String itmNme) {
		set("ITM_NME", itmNme);
	}
	
	/**
	 * 付款计划的名称
	 */
	public java.lang.String getItmNme() {
		return getStr("ITM_NME");
	}

	/**
	 * 预计付款日期
	 */
	public void setPlnDte(java.lang.String plnDte) {
		set("PLN_DTE", plnDte);
	}
	
	/**
	 * 预计付款日期
	 */
	public java.lang.String getPlnDte() {
		return getStr("PLN_DTE");
	}

	/**
	 * 是否关闭
	 */
	public void setIsClr(java.lang.String isClr) {
		set("IS_CLR", isClr);
	}
	
	/**
	 * 是否关闭
	 */
	public java.lang.String getIsClr() {
		return getStr("IS_CLR");
	}

	/**
	 * 内容描述
	 */
	public void setRMK(java.lang.String RMK) {
		set("RMK", RMK);
	}
	
	/**
	 * 内容描述
	 */
	public java.lang.String getRMK() {
		return getStr("RMK");
	}

	/**
	 * 更新人
	 */
	public void setUpdUsr(java.lang.String updUsr) {
		set("UPD_USR", updUsr);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.String getUpdUsr() {
		return getStr("UPD_USR");
	}

	/**
	 * 更新时间
	 */
	public void setUpdDte(java.lang.String updDte) {
		set("UPD_DTE", updDte);
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.String getUpdDte() {
		return getStr("UPD_DTE");
	}

}
