package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInvtrAllocDtl<M extends BaseInvtrAllocDtl<M>> extends Model<M> implements IBean {

	/**
	 * 每一笔库存分配明细
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 每一笔库存分配明细
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 销售订单行项目
	 */
	public void setSoItemId(java.lang.Long soItemId) {
		set("soItemId", soItemId);
	}
	
	/**
	 * 销售订单行项目
	 */
	public java.lang.Long getSoItemId() {
		return getLong("soItemId");
	}

	/**
	 * 库存移动明细
	 */
	public void setMovementItemId(java.lang.Long movementItemId) {
		set("movementItemId", movementItemId);
	}
	
	/**
	 * 库存移动明细
	 */
	public java.lang.Long getMovementItemId() {
		return getLong("movementItemId");
	}

	/**
	 * 类型：分配库存，取消分配库存
	 */
	public void setAllocType(java.lang.String allocType) {
		set("allocType", allocType);
	}
	
	/**
	 * 类型：分配库存，取消分配库存
	 */
	public java.lang.String getAllocType() {
		return getStr("allocType");
	}

	/**
	 * 分配的量
	 */
	public void setAllocQty(java.math.BigDecimal allocQty) {
		set("allocQty", allocQty);
	}
	
	/**
	 * 分配的量
	 */
	public java.math.BigDecimal getAllocQty() {
		return get("allocQty");
	}

	/**
	 * 本次分配的时间
	 */
	public void setAllocDate(java.util.Date allocDate) {
		set("allocDate", allocDate);
	}
	
	/**
	 * 本次分配的时间
	 */
	public java.util.Date getAllocDate() {
		return get("allocDate");
	}

	/**
	 * 本次分配的用户
	 */
	public void setAllocUser(java.lang.String allocUser) {
		set("allocUser", allocUser);
	}
	
	/**
	 * 本次分配的用户
	 */
	public java.lang.String getAllocUser() {
		return getStr("allocUser");
	}

	public void setIsDelivery(java.lang.String isDelivery) {
		set("isDelivery", isDelivery);
	}
	
	public java.lang.String getIsDelivery() {
		return getStr("isDelivery");
	}

}
