package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeptViewer<M extends BaseDeptViewer<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 部门
	 */
	public void setDEPT(java.lang.String DEPT) {
		set("DEPT", DEPT);
	}
	
	/**
	 * 部门
	 */
	public java.lang.String getDEPT() {
		return getStr("DEPT");
	}

	/**
	 * 用户
	 */
	public void setUSR(java.lang.String USR) {
		set("USR", USR);
	}
	
	/**
	 * 用户
	 */
	public java.lang.String getUSR() {
		return getStr("USR");
	}

}
