package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmail<M extends BaseEmail<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 创建时间
	 */
	public void setCreDte(java.lang.String creDte) {
		set("CRE_DTE", creDte);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreDte() {
		return getStr("CRE_DTE");
	}

	/**
	 * 收信人邮箱
	 */
	public void setSendTo(java.lang.String sendTo) {
		set("SEND_TO", sendTo);
	}
	
	/**
	 * 收信人邮箱
	 */
	public java.lang.String getSendTo() {
		return getStr("SEND_TO");
	}

	/**
	 * 收信人姓名
	 */
	public void setUsrNme(java.lang.String usrNme) {
		set("USR_NME", usrNme);
	}
	
	/**
	 * 收信人姓名
	 */
	public java.lang.String getUsrNme() {
		return getStr("USR_NME");
	}

	/**
	 * 主题
	 */
	public void setSUBJ(java.lang.String SUBJ) {
		set("SUBJ", SUBJ);
	}
	
	/**
	 * 主题
	 */
	public java.lang.String getSUBJ() {
		return getStr("SUBJ");
	}

	/**
	 * 描述
	 */
	public void setCTENT(java.lang.String CTENT) {
		set("CTENT", CTENT);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getCTENT() {
		return getStr("CTENT");
	}

	/**
	 * 状态：未发送，已发送
	 */
	public void setSTS(java.lang.String STS) {
		set("STS", STS);
	}
	
	/**
	 * 状态：未发送，已发送
	 */
	public java.lang.String getSTS() {
		return getStr("STS");
	}

	/**
	 * 发送时间
	 */
	public void setSentDte(java.lang.String sentDte) {
		set("SENT_DTE", sentDte);
	}
	
	/**
	 * 发送时间
	 */
	public java.lang.String getSentDte() {
		return getStr("SENT_DTE");
	}

}
