package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMvmtDtl<M extends BaseMvmtDtl<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setOrderId(java.lang.Long orderId) {
		set("orderId", orderId);
	}
	
	public java.lang.Long getOrderId() {
		return getLong("orderId");
	}

	/**
	 * 库存移动单据号
	 */
	public void setOrderNum(java.lang.String orderNum) {
		set("orderNum", orderNum);
	}
	
	/**
	 * 库存移动单据号
	 */
	public java.lang.String getOrderNum() {
		return getStr("orderNum");
	}

	/**
	 * 行项目序号
	 */
	public void setItemSeq(java.lang.Long itemSeq) {
		set("itemSeq", itemSeq);
	}
	
	/**
	 * 行项目序号
	 */
	public java.lang.Long getItemSeq() {
		return getLong("itemSeq");
	}

	/**
	 * 库存移动时间
	 */
	public void setMovementDate(java.util.Date movementDate) {
		set("movementDate", movementDate);
	}
	
	/**
	 * 库存移动时间
	 */
	public java.util.Date getMovementDate() {
		return get("movementDate");
	}

	/**
	 * 移动类型，入库，出库
	 */
	public void setMovementType(java.lang.String movementType) {
		set("movementType", movementType);
	}
	
	/**
	 * 移动类型，入库，出库
	 */
	public java.lang.String getMovementType() {
		return getStr("movementType");
	}

	/**
	 * 物料编码
	 */
	public void setMaterialCode(java.lang.String materialCode) {
		set("materialCode", materialCode);
	}
	
	/**
	 * 物料编码
	 */
	public java.lang.String getMaterialCode() {
		return getStr("materialCode");
	}

	/**
	 * 移动数量
	 */
	public void setMovementQty(java.math.BigDecimal movementQty) {
		set("movementQty", movementQty);
	}
	
	/**
	 * 移动数量
	 */
	public java.math.BigDecimal getMovementQty() {
		return get("movementQty");
	}

	/**
	 * 已分配至订单的数量
	 */
	public void setAllocQty(java.math.BigDecimal allocQty) {
		set("allocQty", allocQty);
	}
	
	/**
	 * 已分配至订单的数量
	 */
	public java.math.BigDecimal getAllocQty() {
		return get("allocQty");
	}

	/**
	 * 操作用户
	 */
	public void setOperateUser(java.lang.String operateUser) {
		set("operateUser", operateUser);
	}
	
	/**
	 * 操作用户
	 */
	public java.lang.String getOperateUser() {
		return getStr("operateUser");
	}

	/**
	 * 操作时间
	 */
	public void setOperateDate(java.util.Date operateDate) {
		set("operateDate", operateDate);
	}
	
	/**
	 * 操作时间
	 */
	public java.util.Date getOperateDate() {
		return get("operateDate");
	}

}
