package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZClientPotential<M extends BaseZClientPotential<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setClientid(java.lang.Integer clientid) {
		set("clientid", clientid);
	}
	
	public java.lang.Integer getClientid() {
		return getInt("clientid");
	}

	public void setIndex01(java.lang.String index01) {
		set("index01", index01);
	}
	
	public java.lang.String getIndex01() {
		return getStr("index01");
	}

	public void setIndex02(java.lang.String index02) {
		set("index02", index02);
	}
	
	public java.lang.String getIndex02() {
		return getStr("index02");
	}

	public void setIndex03(java.lang.String index03) {
		set("index03", index03);
	}
	
	public java.lang.String getIndex03() {
		return getStr("index03");
	}

	public void setIndex04(java.lang.String index04) {
		set("index04", index04);
	}
	
	public java.lang.String getIndex04() {
		return getStr("index04");
	}

	public void setIndex05(java.lang.String index05) {
		set("index05", index05);
	}
	
	public java.lang.String getIndex05() {
		return getStr("index05");
	}

	public void setIndex06(java.lang.String index06) {
		set("index06", index06);
	}
	
	public java.lang.String getIndex06() {
		return getStr("index06");
	}

	public void setIndex07(java.lang.String index07) {
		set("index07", index07);
	}
	
	public java.lang.String getIndex07() {
		return getStr("index07");
	}

}
