package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataLogin<M extends BaseDataLogin<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 日期
	 */
	public void setDay(java.util.Date day) {
		set("day", day);
	}
	
	/**
	 * 日期
	 */
	public java.util.Date getDay() {
		return get("day");
	}

	/**
	 * 每日活跃数
	 */
	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	/**
	 * 每日活跃数
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 每日登录数
	 */
	public void setNum1(java.lang.Integer num1) {
		set("num1", num1);
	}
	
	/**
	 * 每日登录数
	 */
	public java.lang.Integer getNum1() {
		return getInt("num1");
	}

}
