package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSoftInst<M extends BaseSoftInst<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 单据号
	 */
	public void setApplyNum(java.lang.String applyNum) {
		set("APPLY_NUM", applyNum);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getApplyNum() {
		return getStr("APPLY_NUM");
	}

	/**
	 * 申请人
	 */
	public void setApplyUsr(java.lang.String applyUsr) {
		set("APPLY_USR", applyUsr);
	}
	
	/**
	 * 申请人
	 */
	public java.lang.String getApplyUsr() {
		return getStr("APPLY_USR");
	}

	/**
	 * 申请部门
	 */
	public void setDEPT(java.lang.String DEPT) {
		set("DEPT", DEPT);
	}
	
	/**
	 * 申请部门
	 */
	public java.lang.String getDEPT() {
		return getStr("DEPT");
	}

	/**
	 * 部门经理
	 */
	public void setDeptMgr(java.lang.String deptMgr) {
		set("DEPT_MGR", deptMgr);
	}
	
	/**
	 * 部门经理
	 */
	public java.lang.String getDeptMgr() {
		return getStr("DEPT_MGR");
	}

	/**
	 * 岗位
	 */
	public void setPSTN(java.lang.String PSTN) {
		set("PSTN", PSTN);
	}
	
	/**
	 * 岗位
	 */
	public java.lang.String getPSTN() {
		return getStr("PSTN");
	}

	/**
	 * 申请时间
	 */
	public void setApplyDte(java.lang.String applyDte) {
		set("APPLY_DTE", applyDte);
	}
	
	/**
	 * 申请时间
	 */
	public java.lang.String getApplyDte() {
		return getStr("APPLY_DTE");
	}

	/**
	 * 软件名称
	 */
	public void setSoftNme(java.lang.String softNme) {
		set("SOFT_NME", softNme);
	}
	
	/**
	 * 软件名称
	 */
	public java.lang.String getSoftNme() {
		return getStr("SOFT_NME");
	}

	/**
	 * 软件版本
	 */
	public void setSoftVer(java.lang.String softVer) {
		set("SOFT_VER", softVer);
	}
	
	/**
	 * 软件版本
	 */
	public java.lang.String getSoftVer() {
		return getStr("SOFT_VER");
	}

	/**
	 * 软件类型
	 */
	public void setSoftTyp(java.lang.String softTyp) {
		set("SOFT_TYP", softTyp);
	}
	
	/**
	 * 软件类型
	 */
	public java.lang.String getSoftTyp() {
		return getStr("SOFT_TYP");
	}

	/**
	 * 申请理由
	 */
	public void setApplyRson(java.lang.String applyRson) {
		set("APPLY_RSON", applyRson);
	}
	
	/**
	 * 申请理由
	 */
	public java.lang.String getApplyRson() {
		return getStr("APPLY_RSON");
	}

	/**
	 * 备注
	 */
	public void setRMK(java.lang.String RMK) {
		set("RMK", RMK);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRMK() {
		return getStr("RMK");
	}

	/**
	 * 记录人
	 */
	public void setCreUsr(java.lang.String creUsr) {
		set("CRE_USR", creUsr);
	}
	
	/**
	 * 记录人
	 */
	public java.lang.String getCreUsr() {
		return getStr("CRE_USR");
	}

	/**
	 * 记录时间
	 */
	public void setCreDte(java.lang.String creDte) {
		set("CRE_DTE", creDte);
	}
	
	/**
	 * 记录时间
	 */
	public java.lang.String getCreDte() {
		return getStr("CRE_DTE");
	}

}
