package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataMoney<M extends BaseDataMoney<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 月份
	 */
	public void setMoon(java.lang.String moon) {
		set("moon", moon);
	}
	
	/**
	 * 月份
	 */
	public java.lang.String getMoon() {
		return getStr("moon");
	}

	/**
	 * 手机销售额
	 */
	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	/**
	 * 手机销售额
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 电脑销售额
	 */
	public void setNum1(java.lang.Integer num1) {
		set("num1", num1);
	}
	
	/**
	 * 电脑销售额
	 */
	public java.lang.Integer getNum1() {
		return getInt("num1");
	}

	/**
	 * 避孕套销售额
	 */
	public void setNum2(java.lang.Integer num2) {
		set("num2", num2);
	}
	
	/**
	 * 避孕套销售额
	 */
	public java.lang.Integer getNum2() {
		return getInt("num2");
	}

}
