package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsers<M extends BaseUsers<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 工号
	 */
	public void setCDE(java.lang.String CDE) {
		set("CDE", CDE);
	}
	
	/**
	 * 工号
	 */
	public java.lang.String getCDE() {
		return getStr("CDE");
	}

	/**
	 * 姓名
	 */
	public void setNME(java.lang.String NME) {
		set("NME", NME);
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getNME() {
		return getStr("NME");
	}

	/**
	 * 邮箱
	 */
	public void setEMAIL(java.lang.String EMAIL) {
		set("EMAIL", EMAIL);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEMAIL() {
		return getStr("EMAIL");
	}

	/**
	 * 部门
	 */
	public void setDEPT(java.lang.String DEPT) {
		set("DEPT", DEPT);
	}
	
	/**
	 * 部门
	 */
	public java.lang.String getDEPT() {
		return getStr("DEPT");
	}

	/**
	 * 密码？？
	 */
	public void setPASSWORD(java.lang.String PASSWORD) {
		set("PASSWORD", PASSWORD);
	}
	
	/**
	 * 密码？？
	 */
	public java.lang.String getPASSWORD() {
		return getStr("PASSWORD");
	}

	/**
	 * 功能权限
	 */
	public void setPERMISSIONS(java.lang.String PERMISSIONS) {
		set("PERMISSIONS", PERMISSIONS);
	}
	
	/**
	 * 功能权限
	 */
	public java.lang.String getPERMISSIONS() {
		return getStr("PERMISSIONS");
	}

	public void setTITLE(java.lang.String TITLE) {
		set("TITLE", TITLE);
	}
	
	public java.lang.String getTITLE() {
		return getStr("TITLE");
	}

	public void setSvcLine(java.lang.String svcLine) {
		set("SVC_LINE", svcLine);
	}
	
	public java.lang.String getSvcLine() {
		return getStr("SVC_LINE");
	}

}
