package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLaborClaim<M extends BaseLaborClaim<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 用户名
	 */
	public void setUsrNme(java.lang.String usrNme) {
		set("USR_NME", usrNme);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getUsrNme() {
		return getStr("USR_NME");
	}

	/**
	 * 日期
	 */
	public void setBizDte(java.lang.String bizDte) {
		set("BIZ_DTE", bizDte);
	}
	
	/**
	 * 日期
	 */
	public java.lang.String getBizDte() {
		return getStr("BIZ_DTE");
	}

	/**
	 * 项目号
	 */
	public void setProjCde(java.lang.String projCde) {
		set("PROJ_CDE", projCde);
	}
	
	/**
	 * 项目号
	 */
	public java.lang.String getProjCde() {
		return getStr("PROJ_CDE");
	}

	/**
	 * 小时数
	 */
	public void setHourCnt(java.lang.Integer hourCnt) {
		set("HOUR_CNT", hourCnt);
	}
	
	/**
	 * 小时数
	 */
	public java.lang.Integer getHourCnt() {
		return getInt("HOUR_CNT");
	}

	/**
	 * 更新人
	 */
	public void setUpdUsr(java.lang.String updUsr) {
		set("UPD_USR", updUsr);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.String getUpdUsr() {
		return getStr("UPD_USR");
	}

	/**
	 * 更新时间
	 */
	public void setUpdDte(java.lang.String updDte) {
		set("UPD_DTE", updDte);
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.String getUpdDte() {
		return getStr("UPD_DTE");
	}

	/**
	 * 工作说明
	 */
	public void setRMK(java.lang.String RMK) {
		set("RMK", RMK);
	}
	
	/**
	 * 工作说明
	 */
	public java.lang.String getRMK() {
		return getStr("RMK");
	}

	/**
	 * 项目群
	 */
	public void setProjGrp(java.lang.String projGrp) {
		set("PROJ_GRP", projGrp);
	}
	
	/**
	 * 项目群
	 */
	public java.lang.String getProjGrp() {
		return getStr("PROJ_GRP");
	}

	/**
	 * 部门
	 */
	public void setUsrDept(java.lang.String usrDept) {
		set("USR_DEPT", usrDept);
	}
	
	/**
	 * 部门
	 */
	public java.lang.String getUsrDept() {
		return getStr("USR_DEPT");
	}

	public void setUsrTitle(java.lang.String usrTitle) {
		set("USR_TITLE", usrTitle);
	}
	
	public java.lang.String getUsrTitle() {
		return getStr("USR_TITLE");
	}

	public void setUsrSvcLine(java.lang.String usrSvcLine) {
		set("USR_SVC_LINE", usrSvcLine);
	}
	
	public java.lang.String getUsrSvcLine() {
		return getStr("USR_SVC_LINE");
	}

	public void setProjOwner(java.lang.String projOwner) {
		set("PROJ_OWNER", projOwner);
	}
	
	public java.lang.String getProjOwner() {
		return getStr("PROJ_OWNER");
	}

}
