package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArea<M extends BaseArea<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 父级
	 */
	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}
	
	/**
	 * 父级
	 */
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 级别：0=中国,1=省,2=市,3=区
	 */
	public void setLv(java.lang.Integer lv) {
		set("lv", lv);
	}
	
	/**
	 * 级别：0=中国,1=省,2=市,3=区
	 */
	public java.lang.Integer getLv() {
		return getInt("lv");
	}

}
