package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMatWatchlist<M extends BaseMatWatchlist<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 添加时间
	 */
	public void setCreDte(java.lang.String creDte) {
		set("CRE_DTE", creDte);
	}
	
	/**
	 * 添加时间
	 */
	public java.lang.String getCreDte() {
		return getStr("CRE_DTE");
	}

	/**
	 * 添加人
	 */
	public void setCreUsr(java.lang.String creUsr) {
		set("CRE_USR", creUsr);
	}
	
	/**
	 * 添加人
	 */
	public java.lang.String getCreUsr() {
		return getStr("CRE_USR");
	}

	/**
	 * U8中的料号
	 */
	public void setInvCde(java.lang.String invCde) {
		set("INV_CDE", invCde);
	}
	
	/**
	 * U8中的料号
	 */
	public java.lang.String getInvCde() {
		return getStr("INV_CDE");
	}

	public void setRMK(java.lang.String RMK) {
		set("RMK", RMK);
	}
	
	public java.lang.String getRMK() {
		return getStr("RMK");
	}

}
