package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogs<M extends BaseLogs<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setServerDT(java.lang.String serverDT) {
		set("serverDT", serverDT);
	}
	
	public java.lang.String getServerDT() {
		return getStr("serverDT");
	}

	public void setRemoteIP(java.lang.String remoteIP) {
		set("remoteIP", remoteIP);
	}
	
	public java.lang.String getRemoteIP() {
		return getStr("remoteIP");
	}

	public void setFunc(java.lang.String func) {
		set("func", func);
	}
	
	public java.lang.String getFunc() {
		return getStr("func");
	}

	public void setParam(java.lang.String param) {
		set("param", param);
	}
	
	public java.lang.String getParam() {
		return getStr("param");
	}

}
