package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTick<M extends BaseTick<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 采样时刻
	 */
	public void setTickDt(java.lang.String tickDt) {
		set("TICK_DT", tickDt);
	}
	
	/**
	 * 采样时刻
	 */
	public java.lang.String getTickDt() {
		return getStr("TICK_DT");
	}

	/**
	 * MAC
	 */
	public void setMAC(java.lang.String MAC) {
		set("MAC", MAC);
	}
	
	/**
	 * MAC
	 */
	public java.lang.String getMAC() {
		return getStr("MAC");
	}

	/**
	 * cpu使用率
	 */
	public void setCpuLoad(java.lang.Float cpuLoad) {
		set("CPU_LOAD", cpuLoad);
	}
	
	/**
	 * cpu使用率
	 */
	public java.lang.Float getCpuLoad() {
		return getFloat("CPU_LOAD");
	}

	/**
	 * cpu数量
	 */
	public void setCpuNumber(java.lang.Integer cpuNumber) {
		set("CPU_NUMBER", cpuNumber);
	}
	
	/**
	 * cpu数量
	 */
	public java.lang.Integer getCpuNumber() {
		return getInt("CPU_NUMBER");
	}

	/**
	 * cpu类型
	 */
	public void setCpuType(java.lang.String cpuType) {
		set("CPU_TYPE", cpuType);
	}
	
	/**
	 * cpu类型
	 */
	public java.lang.String getCpuType() {
		return getStr("CPU_TYPE");
	}

	/**
	 * cpu等级
	 */
	public void setCpuLevel(java.lang.String cpuLevel) {
		set("CPU_LEVEL", cpuLevel);
	}
	
	/**
	 * cpu等级
	 */
	public java.lang.String getCpuLevel() {
		return getStr("CPU_LEVEL");
	}

	/**
	 * cpu版本
	 */
	public void setCpuRevision(java.lang.String cpuRevision) {
		set("CPU_REVISION", cpuRevision);
	}
	
	/**
	 * cpu版本
	 */
	public java.lang.String getCpuRevision() {
		return getStr("CPU_REVISION");
	}

	/**
	 * 总内存
	 */
	public void setMemoryTotal(java.lang.Float memoryTotal) {
		set("MEMORY_TOTAL", memoryTotal);
	}
	
	/**
	 * 总内存
	 */
	public java.lang.Float getMemoryTotal() {
		return getFloat("MEMORY_TOTAL");
	}

	/**
	 * 内存使用率
	 */
	public void setMemoryUsed(java.lang.Float memoryUsed) {
		set("MEMORY_USED", memoryUsed);
	}
	
	/**
	 * 内存使用率
	 */
	public java.lang.Float getMemoryUsed() {
		return getFloat("MEMORY_USED");
	}

	/**
	 * 活动窗口
	 */
	public void setAppTitle(java.lang.String appTitle) {
		set("APP_TITLE", appTitle);
	}
	
	/**
	 * 活动窗口
	 */
	public java.lang.String getAppTitle() {
		return getStr("APP_TITLE");
	}

}
