package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDispatchlist<M extends BaseDispatchlist<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	public void setDLID(java.lang.Long DLID) {
		set("DLID", DLID);
	}
	
	public java.lang.Long getDLID() {
		return getLong("DLID");
	}

	public void setCCUSCODE(java.lang.String CCUSCODE) {
		set("CCUSCODE", CCUSCODE);
	}
	
	public java.lang.String getCCUSCODE() {
		return getStr("CCUSCODE");
	}

	public void setCCUSNAME(java.lang.String CCUSNAME) {
		set("CCUSNAME", CCUSNAME);
	}
	
	public java.lang.String getCCUSNAME() {
		return getStr("CCUSNAME");
	}

	public void setCBUSTYPE(java.lang.String CBUSTYPE) {
		set("CBUSTYPE", CBUSTYPE);
	}
	
	public java.lang.String getCBUSTYPE() {
		return getStr("CBUSTYPE");
	}

	public void setCMAKER(java.lang.String CMAKER) {
		set("CMAKER", CMAKER);
	}
	
	public java.lang.String getCMAKER() {
		return getStr("CMAKER");
	}

	public void setCMEMO(java.lang.String CMEMO) {
		set("CMEMO", CMEMO);
	}
	
	public java.lang.String getCMEMO() {
		return getStr("CMEMO");
	}

	public void setCPERSONCODE(java.lang.String CPERSONCODE) {
		set("CPERSONCODE", CPERSONCODE);
	}
	
	public java.lang.String getCPERSONCODE() {
		return getStr("CPERSONCODE");
	}

	public void setCSHIPADDRESS(java.lang.String CSHIPADDRESS) {
		set("CSHIPADDRESS", CSHIPADDRESS);
	}
	
	public java.lang.String getCSHIPADDRESS() {
		return getStr("CSHIPADDRESS");
	}

	public void setCVERIFIER(java.lang.String CVERIFIER) {
		set("CVERIFIER", CVERIFIER);
	}
	
	public java.lang.String getCVERIFIER() {
		return getStr("CVERIFIER");
	}

	public void setDVERIFYDATE(java.lang.String DVERIFYDATE) {
		set("DVERIFYDATE", DVERIFYDATE);
	}
	
	public java.lang.String getDVERIFYDATE() {
		return getStr("DVERIFYDATE");
	}

	public void setCMODIFIER(java.lang.String CMODIFIER) {
		set("CMODIFIER", CMODIFIER);
	}
	
	public java.lang.String getCMODIFIER() {
		return getStr("CMODIFIER");
	}

	public void setDMODDATE(java.lang.String DMODDATE) {
		set("DMODDATE", DMODDATE);
	}
	
	public java.lang.String getDMODDATE() {
		return getStr("DMODDATE");
	}

	public void setDDate(java.lang.String dDate) {
		set("dDate", dDate);
	}
	
	public java.lang.String getDDate() {
		return getStr("dDate");
	}

}
