package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCity<M extends BaseCity<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}
	
	public java.lang.String getName() {
		return getStr("Name");
	}

	public void setCountryCode(java.lang.String CountryCode) {
		set("CountryCode", CountryCode);
	}
	
	public java.lang.String getCountryCode() {
		return getStr("CountryCode");
	}

	public void setDistrict(java.lang.String District) {
		set("District", District);
	}
	
	public java.lang.String getDistrict() {
		return getStr("District");
	}

	public void setPopulation(java.lang.Integer Population) {
		set("Population", Population);
	}
	
	public java.lang.Integer getPopulation() {
		return getInt("Population");
	}

}
