package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDispatchlists<M extends BaseDispatchlists<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	public void setIDLSID(java.lang.Long IDLSID) {
		set("IDLSID", IDLSID);
	}
	
	public java.lang.Long getIDLSID() {
		return getLong("IDLSID");
	}

	public void setDLID(java.lang.Long DLID) {
		set("DLID", DLID);
	}
	
	public java.lang.Long getDLID() {
		return getLong("DLID");
	}

	public void setISOSID(java.lang.Long ISOSID) {
		set("ISOSID", ISOSID);
	}
	
	public java.lang.Long getISOSID() {
		return getLong("ISOSID");
	}

	public void setCINVCODE(java.lang.String CINVCODE) {
		set("CINVCODE", CINVCODE);
	}
	
	public java.lang.String getCINVCODE() {
		return getStr("CINVCODE");
	}

	public void setCINVNAME(java.lang.String CINVNAME) {
		set("CINVNAME", CINVNAME);
	}
	
	public java.lang.String getCINVNAME() {
		return getStr("CINVNAME");
	}

	public void setIQUANTITY(java.lang.Integer IQUANTITY) {
		set("IQUANTITY", IQUANTITY);
	}
	
	public java.lang.Integer getIQUANTITY() {
		return getInt("IQUANTITY");
	}

	public void setFOUTQUANTITY(java.lang.Integer FOUTQUANTITY) {
		set("FOUTQUANTITY", FOUTQUANTITY);
	}
	
	public java.lang.Integer getFOUTQUANTITY() {
		return getInt("FOUTQUANTITY");
	}

	public void setCITEMCODE(java.lang.String CITEMCODE) {
		set("CITEMCODE", CITEMCODE);
	}
	
	public java.lang.String getCITEMCODE() {
		return getStr("CITEMCODE");
	}

	public void setCitemClass(java.lang.String citemClass) {
		set("CITEM_CLASS", citemClass);
	}
	
	public java.lang.String getCitemClass() {
		return getStr("CITEM_CLASS");
	}

	public void setCITEMNAME(java.lang.String CITEMNAME) {
		set("CITEMNAME", CITEMNAME);
	}
	
	public java.lang.String getCITEMNAME() {
		return getStr("CITEMNAME");
	}

	public void setCitemCname(java.lang.String citemCname) {
		set("CITEM_CNAME", citemCname);
	}
	
	public java.lang.String getCitemCname() {
		return getStr("CITEM_CNAME");
	}

}
