package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRdrecord32<M extends BaseRdrecord32<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	public void setRDRECORDID(java.lang.Long RDRECORDID) {
		set("RDRECORDID", RDRECORDID);
	}
	
	public java.lang.Long getRDRECORDID() {
		return getLong("RDRECORDID");
	}

	public void setCMAKER(java.lang.String CMAKER) {
		set("CMAKER", CMAKER);
	}
	
	public java.lang.String getCMAKER() {
		return getStr("CMAKER");
	}

	public void setCHANDLER(java.lang.String CHANDLER) {
		set("CHANDLER", CHANDLER);
	}
	
	public java.lang.String getCHANDLER() {
		return getStr("CHANDLER");
	}

	public void setDDATE(java.lang.String DDATE) {
		set("DDATE", DDATE);
	}
	
	public java.lang.String getDDATE() {
		return getStr("DDATE");
	}

	public void setCMEMO(java.lang.String CMEMO) {
		set("CMEMO", CMEMO);
	}
	
	public java.lang.String getCMEMO() {
		return getStr("CMEMO");
	}

	public void setCBUSTYPE(java.lang.String CBUSTYPE) {
		set("CBUSTYPE", CBUSTYPE);
	}
	
	public java.lang.String getCBUSTYPE() {
		return getStr("CBUSTYPE");
	}

	public void setCCUSCODE(java.lang.String CCUSCODE) {
		set("CCUSCODE", CCUSCODE);
	}
	
	public java.lang.String getCCUSCODE() {
		return getStr("CCUSCODE");
	}

	public void setCDLCODE(java.lang.String CDLCODE) {
		set("CDLCODE", CDLCODE);
	}
	
	public java.lang.String getCDLCODE() {
		return getStr("CDLCODE");
	}

	public void setCCUSNAME(java.lang.String CCUSNAME) {
		set("CCUSNAME", CCUSNAME);
	}
	
	public java.lang.String getCCUSNAME() {
		return getStr("CCUSNAME");
	}

}
