package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePricepool<M extends BasePricepool<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	/**
	 * 自动生成的编号，每日流水号；
	 */
	public void setNUM(java.lang.String NUM) {
		set("NUM", NUM);
	}
	
	/**
	 * 自动生成的编号，每日流水号；
	 */
	public java.lang.String getNUM() {
		return getStr("NUM");
	}

	/**
	 * 供应商
	 */
	public void setVNDR(java.lang.String VNDR) {
		set("VNDR", VNDR);
	}
	
	/**
	 * 供应商
	 */
	public java.lang.String getVNDR() {
		return getStr("VNDR");
	}

	/**
	 * SAP 中 供应商编码
	 */
	public void setSapVndrCde(java.lang.String sapVndrCde) {
		set("SAP_VNDR_CDE", sapVndrCde);
	}
	
	/**
	 * SAP 中 供应商编码
	 */
	public java.lang.String getSapVndrCde() {
		return getStr("SAP_VNDR_CDE");
	}

	/**
	 * 物料
	 */
	public void setMAT(java.lang.String MAT) {
		set("MAT", MAT);
	}
	
	/**
	 * 物料
	 */
	public java.lang.String getMAT() {
		return getStr("MAT");
	}

	/**
	 * SAP 中料号
	 */
	public void setSapMatCde(java.lang.String sapMatCde) {
		set("SAP_MAT_CDE", sapMatCde);
	}
	
	/**
	 * SAP 中料号
	 */
	public java.lang.String getSapMatCde() {
		return getStr("SAP_MAT_CDE");
	}

	/**
	 * 品牌
	 */
	public void setMatBrand(java.lang.String matBrand) {
		set("MAT_BRAND", matBrand);
	}
	
	/**
	 * 品牌
	 */
	public java.lang.String getMatBrand() {
		return getStr("MAT_BRAND");
	}

	/**
	 * 规格型号
	 */
	public void setMatSpec(java.lang.String matSpec) {
		set("MAT_SPEC", matSpec);
	}
	
	/**
	 * 规格型号
	 */
	public java.lang.String getMatSpec() {
		return getStr("MAT_SPEC");
	}

	public void setMatUnit(java.lang.String matUnit) {
		set("MAT_UNIT", matUnit);
	}
	
	public java.lang.String getMatUnit() {
		return getStr("MAT_UNIT");
	}

	public void setEffFm(java.lang.String effFm) {
		set("EFF_FM", effFm);
	}
	
	public java.lang.String getEffFm() {
		return getStr("EFF_FM");
	}

	public void setEffTo(java.lang.String effTo) {
		set("EFF_TO", effTo);
	}
	
	public java.lang.String getEffTo() {
		return getStr("EFF_TO");
	}

	public void setIsValid(java.lang.String isValid) {
		set("IS_VALID", isValid);
	}
	
	public java.lang.String getIsValid() {
		return getStr("IS_VALID");
	}

	public void setUpdUsr(java.lang.String updUsr) {
		set("UPD_USR", updUsr);
	}
	
	public java.lang.String getUpdUsr() {
		return getStr("UPD_USR");
	}

	public void setUpdDte(java.lang.String updDte) {
		set("UPD_DTE", updDte);
	}
	
	public java.lang.String getUpdDte() {
		return getStr("UPD_DTE");
	}

	/**
	 * 贸易条款 FOB / CIF
	 */
	public void setTERM(java.lang.String TERM) {
		set("TERM", TERM);
	}
	
	/**
	 * 贸易条款 FOB / CIF
	 */
	public java.lang.String getTERM() {
		return getStr("TERM");
	}

	/**
	 * 交货期
	 */
	public void setDlvDays(java.lang.String dlvDays) {
		set("DLV_DAYS", dlvDays);
	}
	
	/**
	 * 交货期
	 */
	public java.lang.String getDlvDays() {
		return getStr("DLV_DAYS");
	}

	/**
	 * 合同条款
	 */
	public void setCOND(java.lang.String COND) {
		set("COND", COND);
	}
	
	/**
	 * 合同条款
	 */
	public java.lang.String getCOND() {
		return getStr("COND");
	}

	/**
	 * 单价
	 */
	public void setUnitPrice(java.lang.String unitPrice) {
		set("UNIT_PRICE", unitPrice);
	}
	
	/**
	 * 单价
	 */
	public java.lang.String getUnitPrice() {
		return getStr("UNIT_PRICE");
	}

	/**
	 * 币种
	 */
	public void setPriceCcy(java.lang.String priceCcy) {
		set("PRICE_CCY", priceCcy);
	}
	
	/**
	 * 币种
	 */
	public java.lang.String getPriceCcy() {
		return getStr("PRICE_CCY");
	}

	/**
	 * 框架协议号
	 */
	public void setFcNum(java.lang.String fcNum) {
		set("FC_NUM", fcNum);
	}
	
	/**
	 * 框架协议号
	 */
	public java.lang.String getFcNum() {
		return getStr("FC_NUM");
	}

	public void setTXT1(java.lang.String TXT1) {
		set("TXT1", TXT1);
	}
	
	public java.lang.String getTXT1() {
		return getStr("TXT1");
	}

	public void setTXT2(java.lang.String TXT2) {
		set("TXT2", TXT2);
	}
	
	public java.lang.String getTXT2() {
		return getStr("TXT2");
	}

	public void setTXT3(java.lang.String TXT3) {
		set("TXT3", TXT3);
	}
	
	public java.lang.String getTXT3() {
		return getStr("TXT3");
	}

}
