package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEventTodo<M extends BaseEventTodo<M>> extends Model<M> implements IBean {

	public void setEvtTodoId(java.lang.Long evtTodoId) {
		set("EVT_TODO_ID", evtTodoId);
	}
	
	public java.lang.Long getEvtTodoId() {
		return getLong("EVT_TODO_ID");
	}

	/**
	 * 业务参考ID
	 */
	public void setRefId(java.lang.Long refId) {
		set("REF_ID", refId);
	}
	
	/**
	 * 业务参考ID
	 */
	public java.lang.Long getRefId() {
		return getLong("REF_ID");
	}

	/**
	 * 业务参考类型
	 */
	public void setRefTyp(java.lang.String refTyp) {
		set("REF_TYP", refTyp);
	}
	
	/**
	 * 业务参考类型
	 */
	public java.lang.String getRefTyp() {
		return getStr("REF_TYP");
	}

	/**
	 * 业务参考名称
	 */
	public void setRefTitle(java.lang.String refTitle) {
		set("REF_TITLE", refTitle);
	}
	
	/**
	 * 业务参考名称
	 */
	public java.lang.String getRefTitle() {
		return getStr("REF_TITLE");
	}

	/**
	 * 序号
	 */
	public void setTodoSeq(java.lang.Integer todoSeq) {
		set("TODO_SEQ", todoSeq);
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getTodoSeq() {
		return getInt("TODO_SEQ");
	}

	/**
	 * 待办工作描述
	 */
	public void setTodoCtent(java.lang.String todoCtent) {
		set("TODO_CTENT", todoCtent);
	}
	
	/**
	 * 待办工作描述
	 */
	public java.lang.String getTodoCtent() {
		return getStr("TODO_CTENT");
	}

	/**
	 * 责任人
	 */
	public void setOwnerId(java.lang.Long ownerId) {
		set("OWNER_ID", ownerId);
	}
	
	/**
	 * 责任人
	 */
	public java.lang.Long getOwnerId() {
		return getLong("OWNER_ID");
	}

	/**
	 * 责任人
	 */
	public void setOwnerNme(java.lang.String ownerNme) {
		set("OWNER_NME", ownerNme);
	}
	
	/**
	 * 责任人
	 */
	public java.lang.String getOwnerNme() {
		return getStr("OWNER_NME");
	}

	/**
	 * 计划完成时间
	 */
	public void setDueDte(java.lang.String dueDte) {
		set("DUE_DTE", dueDte);
	}
	
	/**
	 * 计划完成时间
	 */
	public java.lang.String getDueDte() {
		return getStr("DUE_DTE");
	}

	/**
	 * 当前状态：OPEN，OVERDUE，CLOSE
	 */
	public void setTodoSts(java.lang.String todoSts) {
		set("TODO_STS", todoSts);
	}
	
	/**
	 * 当前状态：OPEN，OVERDUE，CLOSE
	 */
	public java.lang.String getTodoSts() {
		return getStr("TODO_STS");
	}

	/**
	 * 实际完成日期
	 */
	public void setActCmplDte(java.lang.String actCmplDte) {
		set("ACT_CMPL_DTE", actCmplDte);
	}
	
	/**
	 * 实际完成日期
	 */
	public java.lang.String getActCmplDte() {
		return getStr("ACT_CMPL_DTE");
	}

	/**
	 * 备注
	 */
	public void setMEMO(java.lang.String MEMO) {
		set("MEMO", MEMO);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMEMO() {
		return getStr("MEMO");
	}

	/**
	 * 创建人
	 */
	public void setCreUsr(java.lang.String creUsr) {
		set("CRE_USR", creUsr);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreUsr() {
		return getStr("CRE_USR");
	}

	/**
	 * 创建时间
	 */
	public void setCreDt(java.lang.String creDt) {
		set("CRE_DT", creDt);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreDt() {
		return getStr("CRE_DT");
	}

	/**
	 * 更新人
	 */
	public void setUpdUsr(java.lang.String updUsr) {
		set("UPD_USR", updUsr);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.String getUpdUsr() {
		return getStr("UPD_USR");
	}

	/**
	 * 更新日期
	 */
	public void setUpdDt(java.lang.String updDt) {
		set("UPD_DT", updDt);
	}
	
	/**
	 * 更新日期
	 */
	public java.lang.String getUpdDt() {
		return getStr("UPD_DT");
	}

	/**
	 * 规则是否开启：1 开启，非1都是未开启
	 */
	public void setMatRule(java.lang.String matRule) {
		set("MAT_RULE", matRule);
	}
	
	/**
	 * 规则是否开启：1 开启，非1都是未开启
	 */
	public java.lang.String getMatRule() {
		return getStr("MAT_RULE");
	}

	/**
	 * 物料号
	 */
	public void setMatCode(java.lang.String matCode) {
		set("MAT_CODE", matCode);
	}
	
	/**
	 * 物料号
	 */
	public java.lang.String getMatCode() {
		return getStr("MAT_CODE");
	}

	/**
	 * 物料数量的判断逻辑
	 */
	public void setMatCond(java.lang.String matCond) {
		set("MAT_COND", matCond);
	}
	
	/**
	 * 物料数量的判断逻辑
	 */
	public java.lang.String getMatCond() {
		return getStr("MAT_COND");
	}

}
