package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSbsVcCtrct<M extends BaseSbsVcCtrct<M>> extends Model<M> implements IBean {

	public void setVcCtrctId(java.lang.Integer vcCtrctId) {
		set("VC_CTRCT_ID", vcCtrctId);
	}
	
	public java.lang.Integer getVcCtrctId() {
		return getInt("VC_CTRCT_ID");
	}

	public void setVslId(java.math.BigDecimal vslId) {
		set("VSL_ID", vslId);
	}
	
	public java.math.BigDecimal getVslId() {
		return get("VSL_ID");
	}

	public void setVslCde(java.lang.String vslCde) {
		set("VSL_CDE", vslCde);
	}
	
	public java.lang.String getVslCde() {
		return getStr("VSL_CDE");
	}

	/**
	 * 创建协议的公司
	 */
	public void setCompCde(java.lang.String compCde) {
		set("COMP_CDE", compCde);
	}
	
	/**
	 * 创建协议的公司
	 */
	public java.lang.String getCompCde() {
		return getStr("COMP_CDE");
	}

	/**
	 * 协议号
	 */
	public void setCtrctNum(java.lang.String ctrctNum) {
		set("CTRCT_NUM", ctrctNum);
	}
	
	/**
	 * 协议号
	 */
	public java.lang.String getCtrctNum() {
		return getStr("CTRCT_NUM");
	}

	/**
	 * 相对于Company Code，0:Owner租出船；1:Charter租入船
	 */
	public void setCtrctTyp(java.lang.String ctrctTyp) {
		set("CTRCT_TYP", ctrctTyp);
	}
	
	/**
	 * 相对于Company Code，0:Owner租出船；1:Charter租入船
	 */
	public java.lang.String getCtrctTyp() {
		return getStr("CTRCT_TYP");
	}

	/**
	 * 船东
	 */
	public void setOwnerPrtyId(java.math.BigDecimal ownerPrtyId) {
		set("OWNER_PRTY_ID", ownerPrtyId);
	}
	
	/**
	 * 船东
	 */
	public java.math.BigDecimal getOwnerPrtyId() {
		return get("OWNER_PRTY_ID");
	}

	/**
	 * 租家
	 */
	public void setCharterPrtyId(java.math.BigDecimal charterPrtyId) {
		set("CHARTER_PRTY_ID", charterPrtyId);
	}
	
	/**
	 * 租家
	 */
	public java.math.BigDecimal getCharterPrtyId() {
		return get("CHARTER_PRTY_ID");
	}

	/**
	 * 协议开始时间
	 */
	public void setCtrctStartDt(java.util.Date ctrctStartDt) {
		set("CTRCT_START_DT", ctrctStartDt);
	}
	
	/**
	 * 协议开始时间
	 */
	public java.util.Date getCtrctStartDt() {
		return get("CTRCT_START_DT");
	}

	/**
	 * 协议结束时间-最小
	 */
	public void setCtrctEndMinDt(java.util.Date ctrctEndMinDt) {
		set("CTRCT_END_MIN_DT", ctrctEndMinDt);
	}
	
	/**
	 * 协议结束时间-最小
	 */
	public java.util.Date getCtrctEndMinDt() {
		return get("CTRCT_END_MIN_DT");
	}

	/**
	 * 协议结束时间-最大
	 */
	public void setCtrctEndMaxDt(java.util.Date ctrctEndMaxDt) {
		set("CTRCT_END_MAX_DT", ctrctEndMaxDt);
	}
	
	/**
	 * 协议结束时间-最大
	 */
	public java.util.Date getCtrctEndMaxDt() {
		return get("CTRCT_END_MAX_DT");
	}

	/**
	 * 默认0；失效:1
	 */
	public void setInvalidInd(java.lang.String invalidInd) {
		set("INVALID_IND", invalidInd);
	}
	
	/**
	 * 默认0；失效:1
	 */
	public java.lang.String getInvalidInd() {
		return getStr("INVALID_IND");
	}

	/**
	 * 结算周期描述
	 */
	public void setSetRmk(java.lang.String setRmk) {
		set("SET_RMK", setRmk);
	}
	
	/**
	 * 结算周期描述
	 */
	public java.lang.String getSetRmk() {
		return getStr("SET_RMK");
	}

	/**
	 * 默认0:非锁定；1:锁定
	 */
	public void setLockedInd(java.lang.String lockedInd) {
		set("LOCKED_IND", lockedInd);
	}
	
	/**
	 * 默认0:非锁定；1:锁定
	 */
	public java.lang.String getLockedInd() {
		return getStr("LOCKED_IND");
	}

	/**
	 * 预留字段：第三方
	 */
	public void setPtn3rdPrtyId(java.math.BigDecimal ptn3rdPrtyId) {
		set("PTN_3RD_PRTY_ID", ptn3rdPrtyId);
	}
	
	/**
	 * 预留字段：第三方
	 */
	public java.math.BigDecimal getPtn3rdPrtyId() {
		return get("PTN_3RD_PRTY_ID");
	}

	/**
	 * 预留字段：第四方
	 */
	public void setPtn4thPrtyId(java.math.BigDecimal ptn4thPrtyId) {
		set("PTN_4TH_PRTY_ID", ptn4thPrtyId);
	}
	
	/**
	 * 预留字段：第四方
	 */
	public java.math.BigDecimal getPtn4thPrtyId() {
		return get("PTN_4TH_PRTY_ID");
	}

	/**
	 * 初始化时，起算时间；默认等于合同生效日；以后也不更新
	 */
	public void setSysStupDt(java.util.Date sysStupDt) {
		set("SYS_STUP_DT", sysStupDt);
	}
	
	/**
	 * 初始化时，起算时间；默认等于合同生效日；以后也不更新
	 */
	public java.util.Date getSysStupDt() {
		return get("SYS_STUP_DT");
	}

	/**
	 * 初始化时，期次；默认为1；以后也不更新
	 */
	public void setSysStupIstmtNum(java.math.BigDecimal sysStupIstmtNum) {
		set("SYS_STUP_ISTMT_NUM", sysStupIstmtNum);
	}
	
	/**
	 * 初始化时，期次；默认为1；以后也不更新
	 */
	public java.math.BigDecimal getSysStupIstmtNum() {
		return get("SYS_STUP_ISTMT_NUM");
	}

	/**
	 * 计划交船时间
	 */
	public void setPlnDlvyDt(java.util.Date plnDlvyDt) {
		set("PLN_DLVY_DT", plnDlvyDt);
	}
	
	/**
	 * 计划交船时间
	 */
	public java.util.Date getPlnDlvyDt() {
		return get("PLN_DLVY_DT");
	}

	/**
	 * 计划交船地点
	 */
	public void setPlnDlvyPortCde(java.lang.String plnDlvyPortCde) {
		set("PLN_DLVY_PORT_CDE", plnDlvyPortCde);
	}
	
	/**
	 * 计划交船地点
	 */
	public java.lang.String getPlnDlvyPortCde() {
		return getStr("PLN_DLVY_PORT_CDE");
	}

	/**
	 * 计划还船时间
	 */
	public void setPlnRtnDt(java.util.Date plnRtnDt) {
		set("PLN_RTN_DT", plnRtnDt);
	}
	
	/**
	 * 计划还船时间
	 */
	public java.util.Date getPlnRtnDt() {
		return get("PLN_RTN_DT");
	}

	/**
	 * 计划还船地点
	 */
	public void setPlnRtnPortCde(java.lang.String plnRtnPortCde) {
		set("PLN_RTN_PORT_CDE", plnRtnPortCde);
	}
	
	/**
	 * 计划还船地点
	 */
	public java.lang.String getPlnRtnPortCde() {
		return getStr("PLN_RTN_PORT_CDE");
	}

	/**
	 * 备注信息
	 */
	public void setRMK(java.lang.String RMK) {
		set("RMK", RMK);
	}
	
	/**
	 * 备注信息
	 */
	public java.lang.String getRMK() {
		return getStr("RMK");
	}

	/**
	 * 删除标记Y/N，默认为N
	 */
	public void setDelInd(java.lang.String delInd) {
		set("DEL_IND", delInd);
	}
	
	/**
	 * 删除标记Y/N，默认为N
	 */
	public java.lang.String getDelInd() {
		return getStr("DEL_IND");
	}

	/**
	 * Hibernate版本
	 */
	public void setVerId(java.math.BigDecimal verId) {
		set("VER_ID", verId);
	}
	
	/**
	 * Hibernate版本
	 */
	public java.math.BigDecimal getVerId() {
		return get("VER_ID");
	}

	/**
	 * 创建时间
	 */
	public void setCreAtDt(java.util.Date creAtDt) {
		set("CRE_AT_DT", creAtDt);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreAtDt() {
		return get("CRE_AT_DT");
	}

	/**
	 * 创建人员
	 */
	public void setCreByUsr(java.lang.String creByUsr) {
		set("CRE_BY_USR", creByUsr);
	}
	
	/**
	 * 创建人员
	 */
	public java.lang.String getCreByUsr() {
		return getStr("CRE_BY_USR");
	}

	/**
	 * 更新时间
	 */
	public void setUpdAtDt(java.util.Date updAtDt) {
		set("UPD_AT_DT", updAtDt);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdAtDt() {
		return get("UPD_AT_DT");
	}

	/**
	 * 更新人员
	 */
	public void setUpdByUsr(java.lang.String updByUsr) {
		set("UPD_BY_USR", updByUsr);
	}
	
	/**
	 * 更新人员
	 */
	public java.lang.String getUpdByUsr() {
		return getStr("UPD_BY_USR");
	}

	/**
	 * 时区类型。GMT:Greenwich Mean Time，LOCAL:Local Time
	 */
	public void setTimezoneType(java.lang.String timezoneType) {
		set("TIMEZONE_TYPE", timezoneType);
	}
	
	/**
	 * 时区类型。GMT:Greenwich Mean Time，LOCAL:Local Time
	 */
	public java.lang.String getTimezoneType() {
		return getStr("TIMEZONE_TYPE");
	}

	/**
	 * 还船日期
	 */
	public void setRtnDt(java.util.Date rtnDt) {
		set("RTN_DT", rtnDt);
	}
	
	/**
	 * 还船日期
	 */
	public java.util.Date getRtnDt() {
		return get("RTN_DT");
	}

	/**
	 * 提醒天数
	 */
	public void setRemDays(java.math.BigDecimal remDays) {
		set("REM_DAYS", remDays);
	}
	
	/**
	 * 提醒天数
	 */
	public java.math.BigDecimal getRemDays() {
		return get("REM_DAYS");
	}

}
