package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProj<M extends BaseProj<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Long ID) {
		set("ID", ID);
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	/**
	 * 项目类别
	 */
	public void setProjGrp(java.lang.String projGrp) {
		set("PROJ_GRP", projGrp);
	}
	
	/**
	 * 项目类别
	 */
	public java.lang.String getProjGrp() {
		return getStr("PROJ_GRP");
	}

	/**
	 * 项目号
	 */
	public void setProjCde(java.lang.String projCde) {
		set("PROJ_CDE", projCde);
	}
	
	/**
	 * 项目号
	 */
	public java.lang.String getProjCde() {
		return getStr("PROJ_CDE");
	}

	/**
	 * 项目说明
	 */
	public void setRMK(java.lang.String RMK) {
		set("RMK", RMK);
	}
	
	/**
	 * 项目说明
	 */
	public java.lang.String getRMK() {
		return getStr("RMK");
	}

	public void setOWNER(java.lang.String OWNER) {
		set("OWNER", OWNER);
	}
	
	public java.lang.String getOWNER() {
		return getStr("OWNER");
	}

	public void setProjNme(java.lang.String projNme) {
		set("PROJ_NME", projNme);
	}
	
	public java.lang.String getProjNme() {
		return getStr("PROJ_NME");
	}

	public void setVTYPE(java.lang.String VTYPE) {
		set("VTYPE", VTYPE);
	}
	
	public java.lang.String getVTYPE() {
		return getStr("VTYPE");
	}

	public void setProjType(java.lang.String projType) {
		set("PROJ_TYPE", projType);
	}
	
	public java.lang.String getProjType() {
		return getStr("PROJ_TYPE");
	}

	public void setApplyDte(java.lang.String applyDte) {
		set("APPLY_DTE", applyDte);
	}
	
	public java.lang.String getApplyDte() {
		return getStr("APPLY_DTE");
	}

	public void setClsInd(java.lang.String clsInd) {
		set("CLS_IND", clsInd);
	}
	
	public java.lang.String getClsInd() {
		return getStr("CLS_IND");
	}

}
