package com.demo.common.model;

import com.demo.common.model.base.BaseAccessLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccessLog extends BaseAccessLog<AccessLog> {
	
}
