package com.demo.common.model;

import com.demo.common.model.base.BaseActvyLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActvyLog extends BaseActvyLog<ActvyLog> {
	
}
