package com.demo.common.model;

import com.demo.common.model.base.BaseAreaCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AreaCity extends BaseAreaCity<AreaCity> {
	
}
