package com.demo.common.model;

import com.demo.common.model.base.BaseBpmDelegation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BpmDelegation extends BaseBpmDelegation<BpmDelegation> {
	
}
