package com.demo.common.model;

import com.demo.common.model.base.BaseBpmInsNode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BpmInsNode extends BaseBpmInsNode<BpmInsNode> {
	
}
