package com.demo.common.model;

import com.demo.common.model.base.BaseBpmProcess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BpmProcess extends BaseBpmProcess<BpmProcess> {
	
}
