package com.demo.common.model;

import com.demo.common.model.base.BaseBpmProcessNode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BpmProcessNode extends BaseBpmProcessNode<BpmProcessNode> {
	
}
