package com.demo.common.model;

import com.demo.common.model.base.BaseCountrylanguage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Countrylanguage extends BaseCountrylanguage<Countrylanguage> {
	
}
