package com.demo.common.model;

import com.demo.common.model.base.BaseCtrctPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CtrctPlan extends BaseCtrctPlan<CtrctPlan> {
	
}
