package com.demo.common.model;

import com.demo.common.model.base.BaseCtrctInv;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CtrctInv extends BaseCtrctInv<CtrctInv> {
	
}
