package com.demo.common.model;

import com.demo.common.model.base.BaseDataMoney;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataMoney extends BaseDataMoney<DataMoney> {
	
}
