package com.demo.common.model;

import com.demo.common.model.base.BaseDeptViewer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptViewer extends BaseDeptViewer<DeptViewer> {
	
}
