package com.demo.common.model;

import com.demo.common.model.base.BaseDiskspace;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Diskspace extends BaseDiskspace<Diskspace> {
	
}
