package com.demo.common.model;

import com.demo.common.model.base.BaseDispatchlists;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dispatchlists extends BaseDispatchlists<Dispatchlists> {
	
}
