package com.demo.common.model;

import com.demo.common.model.base.BaseDispatchlist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dispatchlist extends BaseDispatchlist<Dispatchlist> {
	
}
