package com.demo.common.model;

import com.demo.common.model.base.BaseFileMgmt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileMgmt extends BaseFileMgmt<FileMgmt> {
	
}
