package com.demo.common.model;

import com.demo.common.model.base.BaseInvtrAllocDtl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvtrAllocDtl extends BaseInvtrAllocDtl<InvtrAllocDtl> {
	
}
