package com.demo.common.model;

import com.demo.common.model.base.BaseLaborClaim;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LaborClaim extends BaseLaborClaim<LaborClaim> {
	
}
