package com.demo.common.model;

import com.demo.common.model.base.BaseMatWatchlist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MatWatchlist extends BaseMatWatchlist<MatWatchlist> {
	
}
