package com.demo.common.model;

import com.demo.common.model.base.BaseMonthlyPln;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MonthlyPln extends BaseMonthlyPln<MonthlyPln> {
	
}
