package com.demo.common.model;

import com.demo.common.model.base.BasePricepool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pricepool extends BasePricepool<Pricepool> {
	
}
