package com.demo.common.model;

import com.demo.common.model.base.BaseRdrecords32;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rdrecords32 extends BaseRdrecords32<Rdrecords32> {
	
}
