package com.demo.common.model;

import com.demo.common.model.base.BaseRdrecord32;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rdrecord32 extends BaseRdrecord32<Rdrecord32> {
	
}
