package com.demo.common.model;

import com.demo.common.model.base.BaseReviewLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReviewLog extends BaseReviewLog<ReviewLog> {
	
}
