package com.demo.common.model;

import com.demo.common.model.base.BaseSbsFundSetOrdr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SbsFundSetOrdr extends BaseSbsFundSetOrdr<SbsFundSetOrdr> {
	
}
