package com.demo.common.model;

import com.demo.common.model.base.BaseSbsVcCtrct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SbsVcCtrct extends BaseSbsVcCtrct<SbsVcCtrct> {
	
}
