package com.demo.common.model;

import com.demo.common.model.base.BaseShowroom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Showroom extends BaseShowroom<Showroom> {
	
}
