package com.demo.common.model;

import com.demo.common.model.base.BaseSoftInst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoftInst extends BaseSoftInst<SoftInst> {
	
}
