package com.demo.common.model;

import com.demo.common.model.base.BaseSoSomain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoSomain extends BaseSoSomain<SoSomain> {
	
}
