package com.demo.common.model;

import com.demo.common.model.base.BaseSoSodetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoSodetails extends BaseSoSodetails<SoSodetails> {
	
}
