package com.demo.common.model;

import com.demo.common.model.base.BaseSoSodetailsplan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SoSodetailsplan extends BaseSoSodetailsplan<SoSodetailsplan> {
	
}
