package com.demo.common.model;

import com.demo.common.model.base.BaseTestingitm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Testingitm extends BaseTestingitm<Testingitm> {
	
}
