package com.demo.common.model;

import com.demo.common.model.base.BaseTestinghd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Testinghd extends BaseTestinghd<Testinghd> {
	
}
