package com.demo.common.model;

import com.demo.common.model.base.BaseTtPcbaTestInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TtPcbaTestInfo extends BaseTtPcbaTestInfo<TtPcbaTestInfo> {
	
}
