package com.demo.common.model;

import com.demo.common.model.base.BaseZClientPotential;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZClientPotential extends BaseZClientPotential<ZClientPotential> {
	
}
